-- ELIVA SCHOOL — final Supabase setup
-- Run once in Supabase SQL Editor. This script is idempotent and preserves rows.
-- It consolidates the public website, registrations, CRM, recruitment and CMS requirements.

create extension if not exists pgcrypto;

do $$ begin
  create type public.trainer_status as enum ('not_contacted','contacted','meeting_scheduled','work_session_done','validated','to_review','rejected','archived');
exception when duplicate_object then null; end $$;
do $$ begin
  create type public.center_status as enum ('not_contacted','contacted','visited','tested','favorite','rejected','archived');
exception when duplicate_object then null; end $$;

create table if not exists public.categories (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, description text, sort_order integer not null default 0, active boolean not null default true, created_at timestamptz not null default now());
create table if not exists public.trainers (id uuid primary key default gen_random_uuid(), name text not null, slug text not null unique, title text, bio text, photo_url text, credentials jsonb not null default '[]', social_links jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.courses (id uuid primary key default gen_random_uuid(), title text not null, slug text not null unique, excerpt text not null default '', description text, category_id uuid references public.categories(id) on delete set null, trainer_id uuid references public.trainers(id) on delete set null, cover_url text, format text not null default 'presentiel', status text not null default 'draft', featured boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.course_sessions (id uuid primary key default gen_random_uuid(), course_id uuid not null references public.courses(id) on delete cascade, city text not null, venue text, start_date timestamptz not null, end_date timestamptz, duration_label text not null, price numeric(12,2), capacity integer, registration_open boolean not null default true, featured boolean not null default false, created_at timestamptz not null default now());
create table if not exists public.registrations (id uuid primary key default gen_random_uuid(), full_name text not null, phone text not null, email text, wilaya text not null, course_id uuid references public.courses(id) on delete set null, session_id uuid references public.course_sessions(id) on delete set null, preferred_contact_method text not null default 'phone', age_range text, profession text, message text, status text not null default 'new', source text, utm_source text, utm_medium text, utm_campaign text, utm_content text, utm_term text, landing_page text, referrer text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());

alter table public.registrations add column if not exists course_name_snapshot text;
alter table public.registrations add column if not exists study_mode text not null default 'presentiel';
alter table public.registrations add column if not exists consent boolean not null default false;
alter table public.registrations add column if not exists source_page text;
alter table public.registrations add column if not exists internal_notes text;
alter table public.registrations add column if not exists utm_source text;
alter table public.registrations add column if not exists utm_medium text;
alter table public.registrations add column if not exists utm_campaign text;
alter table public.registrations add column if not exists utm_content text;
alter table public.registrations add column if not exists utm_term text;

create table if not exists public.trainers_crm (id uuid primary key default gen_random_uuid(), full_name text not null, phone text, email text, wilaya text, city text, specialty text, skills text[] not null default '{}', courses_can_teach text[] not null default '{}', years_experience numeric(5,1), cv_url text, portfolio_url text, photo_url text, status public.trainer_status not null default 'not_contacted', last_contact_at timestamptz, next_action_at timestamptz, next_action text, pedagogical_quality smallint, field_experience smallint, communication smallint, availability_rating smallint, tariff_rating smallint, expected_fee numeric(12,2), fee_unit text, internal_notes text, is_favorite boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.trainer_interactions (id uuid primary key default gen_random_uuid(), trainer_id uuid not null references public.trainers_crm(id) on delete cascade, type text not null, title text, notes text, interaction_at timestamptz not null default now(), created_at timestamptz not null default now());
create table if not exists public.centers (id uuid primary key default gen_random_uuid(), center_name text not null, wilaya text not null, city text, address text, contact_person text, phone text, whatsapp text, email text, capacity integer, hourly_rate numeric(12,2), daily_rate numeric(12,2), deposit_amount numeric(12,2), currency text not null default 'DZD', has_projector boolean not null default false, has_wifi boolean not null default false, has_air_conditioning boolean not null default false, has_heating boolean not null default false, has_parking boolean not null default false, has_break_area boolean not null default false, has_sound_system boolean not null default false, has_whiteboard boolean not null default false, google_maps_url text, photos text[] not null default '{}', rental_conditions text, status public.center_status not null default 'not_contacted', already_worked_with boolean not null default false, last_rental_at timestamptz, experience_rating smallint, is_favorite boolean not null default false, internal_notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists public.center_interactions (id uuid primary key default gen_random_uuid(), center_id uuid not null references public.centers(id) on delete cascade, type text not null, title text, notes text, amount numeric(12,2), interaction_at timestamptz not null default now(), created_at timestamptz not null default now());

alter table public.courses add column if not exists title_fr text; alter table public.courses add column if not exists title_ar text; alter table public.courses add column if not exists short_description_fr text; alter table public.courses add column if not exists short_description_ar text; alter table public.courses add column if not exists hero_headline_fr text; alter table public.courses add column if not exists hero_headline_ar text; alter table public.courses add column if not exists modules_fr jsonb not null default '[]'; alter table public.courses add column if not exists modules_ar jsonb not null default '[]'; alter table public.courses add column if not exists faq_fr jsonb not null default '[]'; alter table public.courses add column if not exists faq_ar jsonb not null default '[]'; alter table public.courses add column if not exists study_modes text[] not null default '{}'; alter table public.courses add column if not exists wilayas text[] not null default '{}'; alter table public.courses add column if not exists price numeric(12,2); alter table public.courses add column if not exists currency text default 'DZD'; alter table public.courses add column if not exists seats_available integer; alter table public.courses add column if not exists next_session_date date; alter table public.courses add column if not exists cover_image_path text; alter table public.courses add column if not exists seo_title_fr text; alter table public.courses add column if not exists seo_title_ar text; alter table public.courses add column if not exists seo_description_fr text; alter table public.courses add column if not exists seo_description_ar text; alter table public.courses add column if not exists publish_status text not null default 'draft'; alter table public.courses add column if not exists display_order integer not null default 100; alter table public.courses add column if not exists published_at timestamptz;
alter table public.trainers_crm add column if not exists source text not null default 'manual'; alter table public.trainers_crm add column if not exists applied_at timestamptz; alter table public.trainers_crm add column if not exists birth_year integer; alter table public.trainers_crm add column if not exists linkedin_url text; alter table public.trainers_crm add column if not exists website_url text; alter table public.trainers_crm add column if not exists training_mode_preferences text[] not null default '{}'; alter table public.trainers_crm add column if not exists available_wilayas text[] not null default '{}'; alter table public.trainers_crm add column if not exists languages text[] not null default '{}'; alter table public.trainers_crm add column if not exists education_level text; alter table public.trainers_crm add column if not exists certifications_summary text; alter table public.trainers_crm add column if not exists motivation text; alter table public.trainers_crm add column if not exists public_application_id uuid; alter table public.trainers_crm add column if not exists recruitment_consent boolean not null default false; alter table public.trainers_crm add column if not exists is_public boolean not null default false; alter table public.trainers_crm add column if not exists public_slug text; alter table public.trainers_crm add column if not exists public_title_fr text; alter table public.trainers_crm add column if not exists public_title_ar text; alter table public.trainers_crm add column if not exists public_bio_fr text; alter table public.trainers_crm add column if not exists public_bio_ar text; alter table public.trainers_crm add column if not exists public_expertise_fr jsonb not null default '[]'; alter table public.trainers_crm add column if not exists public_expertise_ar jsonb not null default '[]'; alter table public.trainers_crm add column if not exists public_credentials_fr jsonb not null default '[]'; alter table public.trainers_crm add column if not exists public_credentials_ar jsonb not null default '[]'; alter table public.trainers_crm add column if not exists public_photo_path text; alter table public.trainers_crm add column if not exists public_order integer not null default 100; alter table public.trainers_crm add column if not exists public_seo_title_fr text; alter table public.trainers_crm add column if not exists public_seo_title_ar text; alter table public.trainers_crm add column if not exists public_seo_description_fr text; alter table public.trainers_crm add column if not exists public_seo_description_ar text; alter table public.trainers_crm add column if not exists public_published_at timestamptz;

create unique index if not exists trainers_public_slug_unique_idx on public.trainers_crm(public_slug) where public_slug is not null;
create unique index if not exists trainers_public_application_unique_idx on public.trainers_crm(public_application_id) where public_application_id is not null;
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end $$;
create or replace function public.eliva_is_admin() returns boolean language sql stable security invoker set search_path = public as $$ select coalesce((auth.jwt()->'app_metadata'->>'role') = 'admin', false) or lower(coalesce(auth.jwt()->>'email','')) = 'ilyesbelhay97@gmail.com' $$;
revoke execute on function public.eliva_is_admin() from anon;
grant execute on function public.eliva_is_admin() to authenticated;
do $$ begin execute 'drop trigger if exists trainers_crm_set_updated_at on public.trainers_crm'; execute 'create trigger trainers_crm_set_updated_at before update on public.trainers_crm for each row execute function public.set_updated_at()'; execute 'drop trigger if exists centers_set_updated_at on public.centers'; execute 'create trigger centers_set_updated_at before update on public.centers for each row execute function public.set_updated_at()'; execute 'drop trigger if exists registrations_set_updated_at on public.registrations'; execute 'create trigger registrations_set_updated_at before update on public.registrations for each row execute function public.set_updated_at()'; end $$;

alter table public.categories enable row level security; alter table public.trainers enable row level security; alter table public.courses enable row level security; alter table public.course_sessions enable row level security; alter table public.registrations enable row level security; alter table public.trainers_crm enable row level security; alter table public.trainer_interactions enable row level security; alter table public.centers enable row level security; alter table public.center_interactions enable row level security;
drop policy if exists "public_read_courses" on public.courses; create policy "public_read_courses" on public.courses for select to anon, authenticated using (publish_status = 'published');
drop policy if exists "public_read_categories" on public.categories; create policy "public_read_categories" on public.categories for select to anon, authenticated using (active = true);
drop policy if exists "public_read_trainers_legacy" on public.trainers; create policy "public_read_trainers_legacy" on public.trainers for select to anon, authenticated using (true);
drop policy if exists "public_read_sessions" on public.course_sessions; create policy "public_read_sessions" on public.course_sessions for select to anon, authenticated using (registration_open = true);
drop policy if exists "public_insert_registrations" on public.registrations; create policy "public_insert_registrations" on public.registrations for insert to anon, authenticated with check (status = 'new' and consent = true);
drop policy if exists "admin_registrations" on public.registrations; create policy "admin_registrations" on public.registrations for all to authenticated using (coalesce((auth.jwt()->'app_metadata'->>'role') = 'admin', false) or lower(coalesce(auth.jwt()->>'email','')) = 'ilyesbelhay97@gmail.com') with check (coalesce((auth.jwt()->'app_metadata'->>'role') = 'admin', false) or lower(coalesce(auth.jwt()->>'email','')) = 'ilyesbelhay97@gmail.com');
drop policy if exists "admin_trainers_crm" on public.trainers_crm; create policy "admin_trainers_crm" on public.trainers_crm for all to authenticated using (coalesce((auth.jwt()->'app_metadata'->>'role') = 'admin', false) or lower(coalesce(auth.jwt()->>'email','')) = 'ilyesbelhay97@gmail.com') with check (coalesce((auth.jwt()->'app_metadata'->>'role') = 'admin', false) or lower(coalesce(auth.jwt()->>'email','')) = 'ilyesbelhay97@gmail.com');
drop policy if exists "admin_trainer_interactions" on public.trainer_interactions; create policy "admin_trainer_interactions" on public.trainer_interactions for all to authenticated using (coalesce((auth.jwt()->'app_metadata'->>'role') = 'admin', false) or lower(coalesce(auth.jwt()->>'email','')) = 'ilyesbelhay97@gmail.com') with check (coalesce((auth.jwt()->'app_metadata'->>'role') = 'admin', false) or lower(coalesce(auth.jwt()->>'email','')) = 'ilyesbelhay97@gmail.com');
drop policy if exists "admin_centers" on public.centers; create policy "admin_centers" on public.centers for all to authenticated using (coalesce((auth.jwt()->'app_metadata'->>'role') = 'admin', false) or lower(coalesce(auth.jwt()->>'email','')) = 'ilyesbelhay97@gmail.com') with check (coalesce((auth.jwt()->'app_metadata'->>'role') = 'admin', false) or lower(coalesce(auth.jwt()->>'email','')) = 'ilyesbelhay97@gmail.com');
drop policy if exists "admin_center_interactions" on public.center_interactions; create policy "admin_center_interactions" on public.center_interactions for all to authenticated using (coalesce((auth.jwt()->'app_metadata'->>'role') = 'admin', false) or lower(coalesce(auth.jwt()->>'email','')) = 'ilyesbelhay97@gmail.com') with check (coalesce((auth.jwt()->'app_metadata'->>'role') = 'admin', false) or lower(coalesce(auth.jwt()->>'email','')) = 'ilyesbelhay97@gmail.com');

drop view if exists public.public_trainers_cms;
create view public.public_trainers_cms as select id, full_name, public_slug, is_public, public_title_fr, public_title_ar, public_bio_fr, public_bio_ar, public_expertise_fr, public_expertise_ar, public_credentials_fr, public_credentials_ar, public_photo_path, public_order, public_seo_title_fr, public_seo_title_ar, public_seo_description_fr, public_seo_description_ar from public.trainers_crm where is_public = true;
revoke all on public.trainers_crm from anon; revoke all on public.public_trainers_cms from anon; grant select on public.public_trainers_cms to anon, authenticated;
grant select on public.categories, public.trainers, public.courses, public.course_sessions to anon, authenticated; grant insert on public.registrations to anon; grant all on public.registrations, public.trainers_crm, public.trainer_interactions, public.centers, public.center_interactions to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types) values ('trainer-cv','trainer-cv',false,5242880,array['application/pdf']) on conflict (id) do update set public=false, file_size_limit=5242880, allowed_mime_types=array['application/pdf'];
insert into storage.buckets (id, name, public) values ('course-covers','course-covers',true) on conflict (id) do update set public=true;
insert into storage.buckets (id, name, public) values ('trainer-public','trainer-public',true) on conflict (id) do update set public=true;
drop policy if exists "eliva_storage_admin_insert" on storage.objects; create policy "eliva_storage_admin_insert" on storage.objects for insert to authenticated with check ((coalesce((auth.jwt()->'app_metadata'->>'role') = 'admin', false) or lower(coalesce(auth.jwt()->>'email','')) = 'ilyesbelhay97@gmail.com') and bucket_id in ('trainer-cv','course-covers','trainer-public'));
drop policy if exists "eliva_storage_admin_update" on storage.objects; create policy "eliva_storage_admin_update" on storage.objects for update to authenticated using ((coalesce((auth.jwt()->'app_metadata'->>'role') = 'admin', false) or lower(coalesce(auth.jwt()->>'email','')) = 'ilyesbelhay97@gmail.com') and bucket_id in ('trainer-cv','course-covers','trainer-public')) with check ((coalesce((auth.jwt()->'app_metadata'->>'role') = 'admin', false) or lower(coalesce(auth.jwt()->>'email','')) = 'ilyesbelhay97@gmail.com') and bucket_id in ('trainer-cv','course-covers','trainer-public'));
drop policy if exists "eliva_storage_admin_delete" on storage.objects; create policy "eliva_storage_admin_delete" on storage.objects for delete to authenticated using ((coalesce((auth.jwt()->'app_metadata'->>'role') = 'admin', false) or lower(coalesce(auth.jwt()->>'email','')) = 'ilyesbelhay97@gmail.com') and bucket_id in ('trainer-cv','course-covers','trainer-public'));
drop policy if exists "eliva_storage_admin_read_cv" on storage.objects; create policy "eliva_storage_admin_read_cv" on storage.objects for select to authenticated using ((coalesce((auth.jwt()->'app_metadata'->>'role') = 'admin', false) or lower(coalesce(auth.jwt()->>'email','')) = 'ilyesbelhay97@gmail.com') and bucket_id = 'trainer-cv');
drop policy if exists "eliva_storage_public_media_read" on storage.objects; create policy "eliva_storage_public_media_read" on storage.objects for select to anon, authenticated using (bucket_id in ('course-covers','trainer-public'));

create index if not exists registrations_status_created_idx on public.registrations(status, created_at desc); create index if not exists trainers_crm_status_idx on public.trainers_crm(status); create index if not exists centers_wilaya_idx on public.centers(wilaya); create index if not exists courses_publish_status_idx on public.courses(publish_status, display_order);
