import { createClient } from "@/lib/supabase/server";
import Link from "next/link";

const cards = [{ key: "new", label: "Nouvelles inscriptions" }, { key: "contacted", label: "Leads à contacter" }, { key: "confirmed", label: "Confirmés" }, { key: "paid", label: "Payés" }];

export default async function AdminDashboardPage() {
  const supabase = await createClient();
  const counts = await Promise.all(cards.map((card) => supabase.from("registrations").select("id", { count: "exact", head: true }).eq("status", card.key)));
  const { data: recent } = await supabase.from("registrations").select("id, full_name, course_name_snapshot, status, created_at").order("created_at", { ascending: false }).limit(6);
  return <section><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow text-gold-dark">Vue d’ensemble</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.06em] sm:text-5xl">Pilotage ELIVA.</h1><p className="mt-4 max-w-xl text-sm leading-6 text-ink/60">Un espace privé pour suivre les demandes et organiser les ressources de l’académie.</p></div><Link href="/formations" className="text-sm font-semibold text-gold-dark">Voir le site public ↗</Link></div><div className="mt-10 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map((card, index) => <div key={card.key} className="rounded-2xl border border-ink/10 bg-white p-5"><p className="text-sm text-ink/55">{card.label}</p><p className="mt-4 text-4xl font-semibold tracking-[-0.06em]">{counts[index].count ?? 0}</p></div>)}</div><div className="mt-8 grid gap-8 xl:grid-cols-[1.4fr_0.6fr]"><div className="rounded-3xl border border-ink/10 bg-white p-6 sm:p-8"><div className="flex items-center justify-between gap-4"><div><p className="eyebrow text-gold-dark">Activité récente</p><h2 className="mt-2 text-2xl font-semibold tracking-[-0.04em]">Dernières inscriptions</h2></div><Link href="/admin/inscriptions" className="text-sm font-semibold text-gold-dark">Tout voir ↗</Link></div><div className="mt-6 grid gap-3">{recent?.length ? recent.map((item) => <div key={item.id} className="flex flex-col gap-2 border-t border-ink/10 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{item.full_name}</p><p className="text-sm text-ink/55">{item.course_name_snapshot ?? "Formation non précisée"}</p></div><div className="flex items-center gap-3 text-xs text-ink/55"><span className="rounded-full bg-gold/15 px-3 py-1 font-semibold text-ink">{item.status}</span><span>{new Date(item.created_at).toLocaleDateString("fr-FR")}</span></div></div>) : <p className="rounded-xl bg-sand p-4 text-sm text-ink/60">Aucune inscription pour le moment.</p>}</div></div><div className="rounded-3xl bg-ink p-6 text-white sm:p-8"><p className="eyebrow text-gold">Raccourcis</p><div className="mt-6 grid gap-3"><Link href="/admin/inscriptions" className="rounded-xl border border-white/15 px-4 py-3 text-sm font-semibold text-white/80 hover:bg-white/10 hover:text-white">Gérer les inscriptions ↗</Link><Link href="/admin/formateurs" className="rounded-xl border border-white/15 px-4 py-3 text-sm font-semibold text-white/80 hover:bg-white/10 hover:text-white">Ouvrir l’archive formateurs ↗</Link><Link href="/admin/centres" className="rounded-xl border border-white/15 px-4 py-3 text-sm font-semibold text-white/80 hover:bg-white/10 hover:text-white">Gérer les centres ↗</Link></div></div></div></section>;
}
