import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getCmsTrainers } from "@/lib/cms";
import { isLocale, t } from "@/lib/i18n";
import { LocaleNavbar } from "@/components/i18n/locale-navbar";
import { LocaleFooter } from "@/components/i18n/locale-footer";

export async function generateMetadata({ params }: { params: Promise<{ locale: string; slug: string }> }): Promise<Metadata> { const { locale, slug } = await params; if (!isLocale(locale)) return {}; const result = await getCmsTrainers().catch(() => ({ data: [] })); const person = (result.data ?? []).find(row => row.public_slug === slug); if (!person) return {}; const title = locale === "ar" ? person.public_seo_title_ar || person.public_title_ar : person.public_seo_title_fr || person.public_title_fr; const description = locale === "ar" ? person.public_seo_description_ar || person.public_bio_ar : person.public_seo_description_fr || person.public_bio_fr; return { title: title + " | ELIVA SCHOOL", description, alternates: { canonical: "/" + locale + "/formateurs/" + slug, languages: { fr: "/fr/formateurs/" + slug, ar: "/ar/formateurs/" + slug } }, openGraph: { title, description, images: person.public_photo_path ? [person.public_photo_path] : undefined } }; }
export default async function LocalizedTrainer({ params }: { params: Promise<{ locale: string; slug: string }> }) {
  const { locale, slug } = await params; if (!isLocale(locale)) notFound(); const result = await getCmsTrainers().catch(() => ({ data: [] })); const person = (result.data ?? []).find(row => row.public_slug === slug); if (!person) notFound(); const s = t[locale]; const title = locale === "ar" ? person.public_title_ar : person.public_title_fr; const bio = locale === "ar" ? person.public_bio_ar : person.public_bio_fr; const expertise = (locale === "ar" ? person.public_expertise_ar : person.public_expertise_fr) as unknown[]; const credentials = (locale === "ar" ? person.public_credentials_ar : person.public_credentials_fr) as unknown[];
  return <main><LocaleNavbar locale={locale} path={"/" + locale + "/formateurs/" + slug} /><section className="bg-ink py-20 text-white"><div className="section-shell grid gap-10 lg:grid-cols-[.7fr_1.3fr] lg:items-center"><div className="relative aspect-[4/5] max-w-sm overflow-hidden rounded-3xl">{person.public_photo_path && <img src={person.public_photo_path} alt={person.full_name} className="h-full w-full object-cover" />}</div><div><p className="eyebrow text-gold">{s.trainer}</p><h1 className="mt-5 text-5xl font-semibold sm:text-7xl">{person.full_name}</h1><p className="mt-4 text-xl text-gold">{title}</p><p className="mt-7 max-w-2xl text-lg leading-8 text-white/70">{bio}</p></div></div></section><section className="section-shell grid gap-12 py-20 lg:grid-cols-2"><div><p className="eyebrow text-gold-dark">{s.learn}</p><div className="mt-6 grid gap-3">{expertise.map((item, index) => <div key={index} className="rounded-2xl bg-sand p-5">{String(item)}</div>)}</div></div><div><p className="eyebrow text-gold-dark">{s.program}</p><ul className="mt-6 grid gap-4">{credentials.map((item, index) => <li key={index} className="border-b border-ink/10 pb-4">✦ {String(item)}</li>)}</ul></div></section><LocaleFooter locale={locale} /></main>;
}
