import Link from "next/link";
import { requireLmsRole } from "@/lib/lms";
import StudentCoursePlayer from "@/components/lms/student-course-player";

type ModuleRow = { id: string; title_fr: string | null; title_ar: string | null; description_fr: string | null; description_ar: string | null; display_order: number; published: boolean };
type LessonRow = { id: string; module_id: string; title_fr: string | null; title_ar: string | null; description_fr: string | null; description_ar: string | null; lesson_type: string | null; video_provider: string | null; video_asset_id: string | null; video_playback_id: string | null; video_url: string | null; duration_seconds: number | null; display_order: number; published: boolean };
type LiveRow = { id: string; title_fr: string | null; title_ar: string | null; starts_at: string; ends_at: string | null; provider: string | null; join_url: string | null; status: string };

export default async function StudentCoursePage({ params }: { params: Promise<{ locale: string; courseId: string }> }) { const { locale: rawLocale, courseId } = await params; const locale = rawLocale === "ar" ? "ar" : "fr"; const ar = locale === "ar"; const { supabase } = await requireLmsRole("student", locale); const { data: course } = await supabase.from("courses").select("id,title,excerpt,cover_url,slug").eq("id", courseId).maybeSingle(); const { data: moduleData } = await supabase.from("lms_modules").select("id,title_fr,title_ar,description_fr,description_ar,display_order,published").eq("course_id", courseId).eq("published", true).order("display_order"); const modules = (moduleData ?? []) as unknown as ModuleRow[]; const ids=modules.map((module) => module.id); const { data: lessonData }=ids.length?await supabase.from("lms_lessons").select("id,module_id,title_fr,title_ar,description_fr,description_ar,lesson_type,video_provider,video_asset_id,video_playback_id,video_url,duration_seconds,display_order,published").in("module_id",ids).eq("published", true).order("display_order"): {data:[]}; const lessons = (lessonData ?? []) as unknown as LessonRow[]; const { data: liveData }=await supabase.from("lms_live_sessions").select("id,title_fr,title_ar,starts_at,ends_at,provider,join_url,status").eq("course_id",courseId).neq("status","cancelled").order("starts_at"); const lives = (liveData ?? []) as unknown as LiveRow[]; if(!course)return <main className="section-shell py-20">{ar?"الدورة غير موجودة.":"Formation introuvable."}</main>; return <main dir={ar?"rtl":"ltr"} className="min-h-screen bg-background"><header className="bg-ink px-5 py-5 text-white"><div className="mx-auto flex max-w-6xl justify-between"><Link href={`/${locale}/student`} className="text-sm text-white/70">← {ar?"دوراتي":"Mes formations"}</Link><span className="font-semibold tracking-[0.08em]">Meritify <span className="text-gold">ACADEMY</span></span></div></header><section className="mx-auto max-w-6xl px-5 py-12"><p className="eyebrow text-gold-dark">{ar?"دورة نشطة":"Formation active"}</p><h1 className="mt-3 text-4xl font-semibold">{course.title}</h1><p className="mt-4 max-w-3xl text-ink/60">{course.excerpt}</p><StudentCoursePlayer course={course} modules={modules} lessons={lessons} lives={lives} locale={locale}/></section></main>; }
