export type TrainerRecruitmentInput = { full_name: string; phone: string; email: string; wilaya: string; city?: string; birth_year?: number; current_job: string; specialty: string; years_experience: number; professional_bio: string; has_training_experience: "yes" | "no"; training_experience_details?: string; courses_can_teach: string; skills: string; education_level?: string; certifications_summary?: string; linkedin_url: string; website_url: string; languages: string; available_wilayas: string; training_mode_preferences: ("Présentiel" | "En ligne")[]; availability: "Semaine" | "Week-end" | "Flexible"; motivation: string; additional_information?: string; consent: true; website: string };
const bounded = (value: string, min: number, max: number) => value.length >= min && value.length <= max;
export const trainerRecruitmentSchema = {
  safeParse(input: Record<string, unknown>): { success: true; data: TrainerRecruitmentInput } | { success: false } {
    const value = input; const stringValue = (key: string) => typeof value[key] === "string" ? String(value[key]).trim() : ""; const modes = Array.isArray(value.training_mode_preferences) ? value.training_mode_preferences.filter((item): item is "Présentiel" | "En ligne" => item === "Présentiel" || item === "En ligne") : [];
    const numeric = (key: string) => Number(value[key]); const email = stringValue("email"); const phone = stringValue("phone"); const birth = value.birth_year === undefined || value.birth_year === "" ? undefined : Number(value.birth_year);
    const valid = bounded(stringValue("full_name"), 2, 120) && /^\+?213\s?[567]\d[\s\d().-]{7,}$/.test(phone) && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email) && bounded(stringValue("wilaya"), 2, 80) && bounded(stringValue("current_job"), 2, 160) && bounded(stringValue("specialty"), 2, 160) && Number.isFinite(numeric("years_experience")) && numeric("years_experience") >= 0 && numeric("years_experience") <= 80 && bounded(stringValue("professional_bio"), 30, 2000) && (value.has_training_experience === "yes" || value.has_training_experience === "no") && bounded(stringValue("courses_can_teach"), 2, 1000) && bounded(stringValue("skills"), 2, 1000) && bounded(stringValue("languages"), 2, 500) && bounded(stringValue("available_wilayas"), 2, 1000) && modes.length > 0 && ["Semaine", "Week-end", "Flexible"].includes(String(value.availability)) && bounded(stringValue("motivation"), 30, 2000) && value.consent === true && stringValue("website").length === 0 && (!birth || (Number.isInteger(birth) && birth >= 1940 && birth <= new Date().getFullYear()));
    if (!valid) return { success: false };
    return { success: true, data: { full_name: stringValue("full_name"), phone, email, wilaya: stringValue("wilaya"), city: stringValue("city") || undefined, birth_year: birth, current_job: stringValue("current_job"), specialty: stringValue("specialty"), years_experience: numeric("years_experience"), professional_bio: stringValue("professional_bio"), has_training_experience: value.has_training_experience as "yes" | "no", training_experience_details: stringValue("training_experience_details") || undefined, courses_can_teach: stringValue("courses_can_teach"), skills: stringValue("skills"), education_level: stringValue("education_level") || undefined, certifications_summary: stringValue("certifications_summary") || undefined, linkedin_url: stringValue("linkedin_url"), website_url: stringValue("website_url"), languages: stringValue("languages"), available_wilayas: stringValue("available_wilayas"), training_mode_preferences: modes, availability: String(value.availability) as TrainerRecruitmentInput["availability"], motivation: stringValue("motivation"), additional_information: stringValue("additional_information") || undefined, consent: true, website: "" } };
  }
};
