import Image from "next/image";
import Link from "next/link";
import { type Locale, localeLabels, localizePath, t } from "@/lib/i18n";

export function LocaleNavbar({ locale, path = "/" }: { locale: Locale; path?: string }) {
  const other = locale === "fr" ? "ar" : "fr";
  const s = t[locale];
  const prefix = "/" + locale;
  const isActive = (href: string) => path === href || (href !== prefix && path.startsWith(href + "/"));
  const navLinkClass = (href: string) => `rounded-full px-2 py-2 transition-colors ${isActive(href) ? "font-semibold text-gold-dark" : "text-ink/75 hover:text-gold-dark"}`;
  return <header className="sticky top-0 z-30 border-b border-ink/10 bg-background/95 backdrop-blur-md"><div className="section-shell flex min-h-20 items-center gap-3"><Link href={prefix} className="relative h-12 w-32 shrink-0 overflow-hidden rounded-lg bg-white" aria-label="Meritify Academy"><Image src="/brand/meritify-academy-logo-transparent.png" alt="Meritify Academy" fill sizes="128px" className="object-contain p-1" priority /></Link><nav className="hidden flex-1 items-center justify-end gap-4 text-sm lg:flex"><Link className={navLinkClass(prefix + "/formations")} href={prefix + "/formations"} aria-current={isActive(prefix + "/formations") ? "page" : undefined}>{s.navCourses}</Link><Link className={navLinkClass(prefix + "/formateurs")} href={prefix + "/formateurs"} aria-current={isActive(prefix + "/formateurs") ? "page" : undefined}>{s.navTrainers}</Link><Link className={navLinkClass(prefix + "/rejoignez-nous/formateur")} href={prefix + "/rejoignez-nous/formateur"} aria-current={isActive(prefix + "/rejoignez-nous/formateur") ? "page" : undefined}>{s.navJoinLink}</Link><Link className={navLinkClass(prefix + "/a-propos")} href={prefix + "/a-propos"} aria-current={isActive(prefix + "/a-propos") ? "page" : undefined}>{s.navAbout}</Link><Link className={navLinkClass(prefix + "/contact")} href={prefix + "/contact"} aria-current={isActive(prefix + "/contact") ? "page" : undefined}>{s.navContact}</Link></nav><Link href={localizePath(path, locale, other)} className="ms-auto inline-flex min-h-10 shrink-0 items-center justify-center rounded-full border border-gold/60 px-3 text-sm font-semibold text-gold-dark hover:bg-gold/10 lg:ms-0" aria-label={locale === "fr" ? "Passer à l’arabe" : "Passer au français"}>{localeLabels[locale]} <span className="mx-1 text-ink/30">|</span> {localeLabels[other]}</Link><details className="relative lg:hidden"><summary className="flex h-11 w-11 cursor-pointer list-none items-center justify-center rounded-full border border-ink/20 text-xl" aria-label={locale === "fr" ? "Menu" : "القائمة"}>☰</summary><nav className="absolute end-0 top-14 w-64 rounded-2xl border border-ink/10 bg-white p-3 shadow-2xl"><Link className={`block rounded-xl p-3 ${navLinkClass(prefix + "/formations")}`} href={prefix + "/formations"}>{s.navCourses}</Link><Link className={`block rounded-xl p-3 ${navLinkClass(prefix + "/formateurs")}`} href={prefix + "/formateurs"}>{s.navTrainers}</Link><Link className={`block rounded-xl p-3 ${navLinkClass(prefix + "/rejoignez-nous/formateur")}`} href={prefix + "/rejoignez-nous/formateur"}>{s.navJoinLink}</Link><Link className={`block rounded-xl p-3 ${navLinkClass(prefix + "/a-propos")}`} href={prefix + "/a-propos"}>{s.navAbout}</Link><Link className="mt-2 block rounded-xl bg-ink p-3 font-semibold text-white" href={prefix + "/formations"}>{s.navCta}</Link></nav></details></div></header>;
}



