import Image from "next/image";
import Link from "next/link";
import { type Locale, t } from "@/lib/i18n";

export function LocaleFooter({ locale }: { locale: Locale }) {
  const s = t[locale];
  const prefix = "/" + locale;
  return <footer className="bg-ink py-16 text-white sm:py-20"><div className="section-shell"><div className="grid gap-12 lg:grid-cols-[1.4fr_1fr_1fr_1fr]"><div><Image src="/eliva-logo.png" alt="ELIVA SCHOOL" width={170} height={64} className="rounded-xl bg-white object-contain p-2" /><p className="mt-6 max-w-sm text-sm leading-7 text-white/55">{locale === "fr" ? "Une école de compétences pratiques pour celles et ceux qui veulent faire bouger les choses." : "مدرسة للمهارات العملية لكل من يريد صناعة مستقبله."}</p><Link href={prefix + "/formations"} className="mt-7 inline-flex rounded-full bg-gold px-5 py-3 text-sm font-semibold text-ink hover:bg-white">{s.navCta} ↗</Link></div><div><p className="eyebrow text-gold">{locale === "fr" ? "Explorer" : "استكشف"}</p><div className="mt-5 grid gap-3 text-sm text-white/65"><Link href={prefix + "/formations"} className="hover:text-gold">{s.navCourses}</Link><Link href={prefix + "/formateurs"} className="hover:text-gold">{s.navTrainers}</Link><Link href={prefix + "/faq"} className="hover:text-gold">{s.faq}</Link></div></div><div><p className="eyebrow text-gold">{locale === "fr" ? "Le réseau" : "الشبكة"}</p><div className="mt-5 grid gap-3 text-sm text-white/65"><Link href={prefix + "/rejoignez-nous/formateur"} className="hover:text-gold">{s.navJoinLink}</Link><Link href={prefix + "/a-propos"} className="hover:text-gold">{s.navAbout}</Link><Link href={prefix + "/services"} className="hover:text-gold">{locale === "fr" ? "Services" : "خدماتنا"}</Link></div></div><div><p className="eyebrow text-gold">{s.navContact}</p><a className="mt-5 block text-sm text-white/65 hover:text-gold" href="mailto:bonjour@eliva.school">bonjour@eliva.school</a></div></div><div className="mt-16 flex flex-col gap-3 border-t border-white/10 pt-6 text-xs text-white/40 sm:flex-row sm:items-center sm:justify-between"><span>© ELIVA SCHOOL</span><span>{locale === "fr" ? "Apprendre aujourd’hui. Construire demain." : "تعلّم اليوم. ابنِ الغد."}</span></div></div></footer>;
}
