import type { CourseFaq, CourseModule } from "@/lib/courses";

export type DetailedCourseModule = CourseModule & { lessons: string[] };

export type DetailedCourseContent = {
  presentation: string;
  objectives: string[];
  modules: DetailedCourseModule[];
  skills: string[];
  audience: string[];
  methodology: string[];
  practicalInfo: string[];
  certification?: string;
  faqs: CourseFaq[];
};

// The helper name mirrors the domain concept; the rule targets the Node.js module binding.
// eslint-disable-next-line @next/next/no-assign-module-variable
const module = (title: string, description: string, lessons: string[]): DetailedCourseModule => ({ title, description, lessons });
const faq = (question: string, answer: string): CourseFaq => ({ question, answer });

const fr: Record<string, DetailedCourseContent> = {
  "formation-de-formateurs-tot": {
    presentation: "Une formation intensive destinée aux personnes qui souhaitent développer leurs compétences en animation, communication et conception de formations. Le programme accompagne le participant depuis la préparation d’une formation jusqu’à son animation devant un groupe, avec une forte dimension pratique.",
    objectives: ["Structurer une formation professionnelle", "Identifier les besoins des participants", "Définir des objectifs pédagogiques", "Améliorer la prise de parole en public", "Développer la confiance en soi", "Maîtriser les bases de la communication du formateur", "Gérer un groupe et les situations en salle", "Utiliser efficacement le langage verbal et non verbal", "Concevoir ses supports et son kit de formation", "Construire une méthodologie d’animation"],
    modules: [
      module("Module 01 — Le métier de formateur", "Comprendre la posture et les responsabilités du formateur.", ["Rôle et responsabilités", "Compétences essentielles", "Posture professionnelle", "Qualités d’un formateur efficace"]),
      module("Module 02 — Analyse des besoins", "Partir du besoin réel pour construire un parcours utile.", ["Identifier les besoins", "Comprendre le profil des participants", "Définir les résultats attendus"]),
      module("Module 03 — Objectifs pédagogiques", "Transformer un besoin en objectifs observables et progressifs.", ["Transformer un besoin en objectif", "Structurer les objectifs d’apprentissage", "Organiser la progression pédagogique"]),
      module("Module 04 — Conception d’une formation", "Construire un plan clair et une séance cohérente.", ["Construire un plan de formation", "Structurer une séance", "Préparer le contenu", "Organiser le temps"]),
      module("Module 05 — Méthodologie de formation", "Choisir des méthodes qui favorisent la participation.", ["Méthodes pédagogiques", "Techniques d’animation", "Apprentissage participatif", "Exercices et mises en situation"]),
      module("Module 06 — Prise de parole en public", "Développer une présence claire et convaincante.", ["Préparer son intervention", "Gérer le stress", "Captiver l’audience", "Utiliser la voix", "Développer son aisance"]),
      module("Module 07 — Communication et langage corporel", "Aligner le verbal, le non-verbal et la posture.", ["Communication verbale et non verbale", "Gestuelle et regard", "Posture", "Occupation de l’espace"]),
      module("Module 08 — Gestion du groupe", "Créer un cadre interactif et gérer les situations délicates.", ["Créer de l’interaction", "Maintenir l’attention", "Gérer les questions", "Adapter son animation"]),
      module("Module 09 — Gestion du temps", "Piloter les séquences et garder le rythme.", ["Organiser les séquences", "Respecter le timing", "Prioriser les activités", "Adapter le programme"]),
      module("Module 10 — Introduction à la PNL appliquée", "Découvrir des repères de communication applicables à la formation.", ["Principes utiles à la communication", "Compréhension des profils", "Adaptation du message"]),
      module("Module 11 — Kit du formateur", "Préparer des supports et une organisation fiable.", ["Supports et documents pédagogiques", "Organisation du matériel", "Checklist avant formation"]),
      module("Module 12 — Mise en situation pratique", "Mettre en œuvre une mini-formation et progresser grâce au feedback.", ["Préparer une mini-formation", "Présenter devant le groupe", "Recevoir du feedback", "Améliorer sa prestation"]),
    ],
    skills: ["Concevoir une formation", "Animer un groupe", "Prendre la parole avec aisance", "Créer des supports pédagogiques", "Gérer le temps et les interactions"],
    audience: ["Futurs formateurs", "Professionnels et consultants", "Coachs et managers", "Experts souhaitant transmettre leur expérience"],
    methodology: ["Apports structurés", "Exercices et simulations", "Mises en situation devant le groupe", "Feedback et amélioration progressive"],
    practicalInfo: ["Plus de 30 heures de formation intensive", "Format présentiel", "Programme animé par Djebbour Mohamed", "Dates et lieu selon la session configurée"],
    certification: "Les certificats affichés correspondent à la configuration actuelle du parcours. Toute accréditation optionnelle reste soumise aux modalités indiquées par Meritify Academy.",
    faqs: [faq("À qui s’adresse cette formation ?", "Aux futurs formateurs et aux professionnels qui souhaitent mieux transmettre leur expertise."), faq("La formation est-elle pratique ?", "Oui, le programme combine exercices, simulations et mises en situation."), faq("L’accréditation internationale est-elle incluse ?", "Elle n’est pas présentée comme incluse ; consultez l’équipe pour les modalités configurées de la session.")],
  },
  "agent-de-voyage": {
    presentation: "Une formation pratique destinée aux personnes souhaitant découvrir le fonctionnement d’une agence de voyage et acquérir les compétences essentielles du métier, de la relation client à la conception de produits touristiques.",
    objectives: ["Comprendre le fonctionnement d’une agence de voyage", "Découvrir l’environnement réglementaire du secteur", "Comprendre les produits touristiques", "Développer les techniques de vente", "Comprendre les bases de la tarification", "S’initier aux outils professionnels", "Développer une approche commerciale et marketing"],
    modules: [
      module("Module 01 — Introduction au métier d’agent de voyage", "Découvrir les missions, l’organisation et l’écosystème du métier.", ["Missions de l’agent", "Organisation d’une agence", "Relation avec les clients", "Acteurs du secteur"]),
      module("Module 02 — Création et fonctionnement d’une agence", "Structurer les opérations quotidiennes d’une agence.", ["Organisation administrative", "Procédures essentielles", "Gestion quotidienne", "Documents professionnels"]),
      module("Module 03 — Réglementation et environnement touristique", "Identifier les repères professionnels et les responsabilités.", ["Cadre professionnel", "Responsabilités", "Documents nécessaires", "Relations avec les partenaires"]),
      module("Module 04 — Produits touristiques", "Comprendre et présenter les principales offres de voyage.", ["Billetterie", "Hébergement", "Circuits et séjours", "Transferts", "Packages touristiques"]),
      module("Module 05 — Réservation et tarification", "Acquérir les premières bases de lecture et de tarification.", ["Principes de réservation", "Informations de voyage", "Disponibilités", "Bases de la tarification"]),
      module("Module 06 — Outils professionnels et introduction à Amadeus", "Découvrir la logique d’un système de réservation sans revendiquer une certification officielle.", ["Environnement de travail", "Logique d’un système de réservation", "Lecture des disponibilités", "Opérations essentielles"]),
      module("Module 07 — Vente et marketing touristique", "Transformer le besoin client en proposition claire.", ["Identifier le besoin", "Construire une proposition", "Argumentation commerciale", "Relation et fidélisation", "Marketing d’agence"]),
    ],
    skills: ["Accueillir et conseiller un client", "Présenter une offre touristique", "Lire des informations de réservation", "Construire une proposition commerciale", "Participer à la gestion d’une agence"],
    audience: ["Professionnels du tourisme", "Responsables ou collaborateurs d’agence", "Personnes souhaitant lancer une agence", "Débutants motivés par le secteur du voyage"],
    methodology: ["Études de cas professionnelles", "Démonstrations et exercices", "Simulations de relation client", "Échanges d’expériences"],
    practicalInfo: ["Environ 30 heures selon le format de session", "5 jours intensifs selon la session configurée", "Format présentiel", "Programme animé par Amina Mghizili"],
    certification: "Une attestation de formation professionnelle est indiquée dans la configuration actuelle du parcours. Aucune certification officielle d’outil n’est revendiquée sans confirmation dédiée.",
    faqs: [faq("À qui s’adresse ce parcours ?", "Aux professionnels du tourisme et aux personnes souhaitant découvrir ou développer une activité d’agence."), faq("Amadeus est-il enseigné ?", "Le programme propose une introduction à la logique des outils de réservation ; il ne revendique pas une certification officielle Amadeus."), faq("Quelle est l’approche pédagogique ?", "La formation combine pratique, études de cas, simulations et échanges d’expériences.")],
  },
  photographie: {
    presentation: "Une formation intensive et pratique permettant de comprendre les fondamentaux de la photographie et de progresser de la prise de vue jusqu’au traitement de l’image.",
    objectives: ["Comprendre son appareil photo", "Maîtriser le triangle d’exposition", "Améliorer la mise au point et la netteté", "Composer des images équilibrées", "Utiliser la lumière naturelle et artificielle", "Réaliser des prises de vue en studio et sur le terrain", "Découvrir un workflow de retouche", "Structurer une activité photographique"],
    modules: [
      module("Module 01 — Comprendre son appareil photo", "Prendre en main le matériel et ses réglages essentiels.", ["Types d’appareils", "Objectifs", "Réglages essentiels", "Modes de prise de vue"]),
      module("Module 02 — Triangle d’exposition", "Comprendre l’équilibre entre ouverture, vitesse et ISO.", ["Ouverture", "Vitesse d’obturation", "ISO", "Équilibre de l’exposition"]),
      module("Module 03 — Mise au point et netteté", "Contrôler la netteté selon le sujet et la situation.", ["Autofocus", "Zones de mise au point", "Profondeur de champ", "Netteté"]),
      module("Module 04 — Composition photographique", "Construire une image lisible et expressive.", ["Règle des tiers", "Cadrage", "Perspective", "Lignes", "Équilibre visuel"]),
      module("Module 05 — Lumière", "Lire et modeler la lumière pour servir l’image.", ["Lumière naturelle", "Lumière artificielle", "Direction", "Intensité", "Ombres"]),
      module("Module 06 — Photographie en studio", "Installer une scène et pratiquer avec un éclairage contrôlé.", ["Installation", "Éclairage", "Positionnement", "Exercices pratiques"]),
      module("Module 07 — Photographie de produits", "Produire des images adaptées au e-commerce et aux réseaux sociaux.", ["Mise en scène", "Éclairage produit", "Angles", "Photos de produit"]),
      module("Module 08 — Photographie extérieure", "Préparer une sortie et composer dans une situation réelle.", ["Préparation", "Lumière naturelle", "Composition sur le terrain"]),
      module("Module 09 — Retouche avec Photoshop", "Mettre en place un workflow de corrections essentielles.", ["Workflow", "Corrections", "Couleur", "Contraste", "Retouche"]),
      module("Module 10 — IA et photographie", "Découvrir des outils utiles pour optimiser le workflow et soutenir la créativité.", ["Outils IA utiles", "Optimisation du workflow", "Assistance créative"]),
      module("Module 11 — Transformer la photographie en activité", "Présenter son travail et poser les bases d’une offre.", ["Portfolio", "Présentation du travail", "Relation client", "Bases de tarification", "Réseaux sociaux"]),
    ],
    skills: ["Régler un appareil", "Exposer et composer", "Photographier en studio et sur le terrain", "Retoucher une image", "Présenter une offre photographique"],
    audience: ["Débutants", "Créateurs de contenu", "Entrepreneurs", "Photographes souhaitant structurer leur pratique"],
    methodology: ["Démonstrations guidées", "Exercices en studio", "Sorties pratiques selon la session", "Analyse et retours sur les images"],
    practicalInfo: ["4 jours intensifs", "09:00–12:00 puis 13:00–16:00", "Studio équipé selon la session", "Deux sorties pratiques lorsque prévues dans la session", "Programme animé par Toufik Derdour"],
    faqs: [faq("La formation convient-elle aux débutants ?", "Oui, elle commence par les bases et progresse vers la pratique et le workflow."), faq("La pratique est-elle incluse ?", "Oui, le parcours prévoit des exercices en studio et des sorties pratiques lorsqu’elles sont incluses dans la session."), faq("Quel est l’horaire ?", "L’horaire indicatif est de 09:00 à 12:00 puis de 13:00 à 16:00.")],
  },
  "educatrice-enfants-gerante-creche": {
    presentation: "Un parcours pratique 5 en 1 pour développer des compétences complémentaires dans la petite enfance, de l’accompagnement de l’enfant à l’organisation d’une structure d’accueil.",
    objectives: ["Comprendre les besoins fondamentaux de l’enfant", "Accompagner le développement moteur, cognitif et émotionnel", "Organiser des activités adaptées à l’âge", "Gérer un groupe d’enfants", "Préparer des activités préscolaires", "Découvrir les principes Montessori et Glenn Doman", "Organiser le quotidien d’une crèche", "Communiquer avec les parents"],
    modules: [
      module("Module 01 — Introduction à la petite enfance", "Poser le cadre du métier et de la responsabilité professionnelle.", ["Rôle de l’éducatrice", "Besoins fondamentaux", "Responsabilité professionnelle"]),
      module("Module 02 — Développement de l’enfant", "Observer les grandes dimensions du développement.", ["Développement moteur", "Développement cognitif", "Développement émotionnel", "Développement social"]),
      module("Module 03 — Gestion d’un groupe d’enfants", "Créer un cadre sécurisant et structuré.", ["Organisation", "Routines", "Communication", "Gestion des comportements"]),
      module("Module 04 — Activités éducatives", "Concevoir des ateliers qui favorisent l’éveil et la créativité.", ["Activités sensorielles", "Activités motrices", "Jeux éducatifs", "Créativité", "Organisation d’ateliers"]),
      module("Module 05 — Préparatoire et préscolaire", "Accompagner les premiers apprentissages selon l’âge.", ["Préparation aux apprentissages", "Langage", "Premiers concepts", "Activités adaptées"]),
      module("Module 06 — Montessori", "Découvrir les principes d’autonomie et d’apprentissage par l’activité.", ["Principes généraux", "Environnement", "Autonomie", "Activités pratiques"]),
      module("Module 07 — Glenn Doman", "Présenter les principes et les activités adaptées à la méthode.", ["Introduction à la méthode", "Principes d’utilisation", "Activités adaptées"]),
      module("Module 08 — Gestion d’une crèche ou d’un jardin d’enfants", "Organiser les opérations et la relation avec les parents.", ["Organisation", "Planning", "Communication avec les parents", "Gestion quotidienne"]),
      module("Module 09 — Mise en pratique", "Relier les notions à des situations professionnelles.", ["Cas pratiques", "Préparation d’activités", "Simulation de situations professionnelles"]),
    ],
    skills: ["Accompagner l’enfant", "Préparer des activités éducatives", "Gérer un groupe", "Organiser une structure d’accueil", "Communiquer avec les parents"],
    audience: ["Éducatrices et animatrices", "Responsables de crèche", "Enseignantes préparatoires et préscolaires", "Personnes souhaitant travailler dans la petite enfance"],
    methodology: ["Repères pédagogiques structurés", "Ateliers et cas pratiques", "Préparation d’activités", "Simulations de situations professionnelles"],
    practicalInfo: ["4 jours intensifs", "09:00–15:00", "Parcours configuré en 5 axes complémentaires", "Programme animé par Safa Belkharchouche"],
    faqs: [faq("Que signifie 5 en 1 ?", "Le parcours couvre l’éducation en crèche, la gestion d’un jardin d’enfants, le préscolaire, Montessori et Glenn Doman."), faq("Quel est l’horaire ?", "La durée indicative est de quatre jours intensifs, de 09:00 à 15:00."), faq("La formation est-elle pratique ?", "Oui, elle associe repères pédagogiques, préparation d’activités et simulations professionnelles.")],
  },
  "ecommerce-marketing-digital": {
    presentation: "Une formation pratique conçue pour apprendre à construire et développer un projet e-commerce adapté au marché algérien, depuis le choix du marché jusqu’à l’acquisition client et l’analyse des campagnes publicitaires.",
    objectives: ["Comprendre les fondamentaux du e-commerce", "Choisir une niche et valider une opportunité", "Rechercher des produits et des fournisseurs", "Construire une offre et une boutique", "Créer des contenus publicitaires", "Lancer des campagnes Meta et TikTok", "Lire les performances et optimiser", "Utiliser l’IA comme assistance marketing", "Organiser les opérations et la relation client"],
    modules: [
      module("Module 01 — Fondamentaux du e-commerce", "Comprendre le modèle et organiser un projet réaliste.", ["Modèle e-commerce", "Écosystème", "Organisation d’un projet", "Erreurs fréquentes"]),
      module("Module 02 — Choisir sa niche", "Analyser la demande, la concurrence et le positionnement.", ["Analyse du marché", "Opportunité", "Demande", "Concurrence", "Positionnement"]),
      module("Module 03 — Recherche de produits", "Évaluer un produit avant de construire une offre.", ["Critères d’un produit", "Analyse concurrentielle", "Validation", "Recherche d’opportunités"]),
      module("Module 04 — Sourcing en Algérie", "Structurer une recherche de fournisseurs locaux.", ["Fournisseurs", "Grossistes et fabricants", "Négociation", "Organisation du sourcing"]),
      module("Module 05 — Sourcing et importation depuis la Chine", "Découvrir le sourcing international sans constituer un conseil juridique ou douanier.", ["Recherche de fournisseurs", "Évaluation", "Communication", "Principes de commande"]),
      module("Module 06 — Branding", "Créer une perception de marque cohérente et différenciante.", ["Positionnement", "Identité", "Offre", "Différenciation", "Perception"]),
      module("Module 07 — Création de contenus publicitaires", "Transformer une proposition en créatifs orientés conversion.", ["Hooks", "Angles marketing", "Images et vidéos", "Concepts UGC", "Copywriting", "CTA"]),
      module("Module 08 — Création et optimisation de la boutique", "Construire une expérience claire, rassurante et mobile.", ["Structure", "Page produit", "Offre", "Confiance", "UX mobile", "Conversion"]),
      module("Module 09 — Facebook et Instagram Ads", "Lancer, tester et lire des campagnes publicitaires.", ["Structure publicitaire", "Campagnes", "Audiences", "Créatifs", "Tests", "Résultats"]),
      module("Module 10 — TikTok Ads", "Adapter les créatifs et les campagnes à TikTok.", ["Principes", "Créatifs adaptés", "Campagnes", "Tests", "Analyse"]),
      module("Module 11 — Analyse des performances", "Prendre des décisions à partir des indicateurs utiles.", ["KPI", "Coût d’acquisition", "Conversion", "Analyse des créatifs", "Décisions basées sur les données"]),
      module("Module 12 — Scaling", "Développer progressivement une campagne prometteuse.", ["Identifier une campagne", "Optimisation", "Augmentation progressive", "Diversification créative"]),
      module("Module 13 — Intelligence artificielle pour l’e-commerce", "Utiliser l’IA pour gagner en recherche, analyse et productivité.", ["Recherche", "Analyse", "Copywriting", "Concepts", "Productivité", "Assistance marketing"]),
      module("Module 14 — Organisation opérationnelle", "Structurer la commande, la livraison et la relation client.", ["Commandes", "Confirmation", "Livraison", "Suivi", "Retours", "Relation client"]),
    ],
    skills: ["Analyser une niche", "Valider un produit", "Construire une boutique", "Créer des créatifs", "Lancer et lire des campagnes", "Optimiser une offre"],
    audience: ["Débutants", "Porteurs de projet", "Vendeurs en ligne", "Personnes souhaitant lancer ou structurer un business e-commerce"],
    methodology: ["Plus de 30 heures de pratique", "Démonstrations et ateliers", "Cas orientés marché", "Suivi et ressources selon la configuration actuelle du parcours"],
    practicalInfo: ["Parcours réparti sur environ un mois", "Présentiel complété par des ressources en ligne", "Programme animé par Ilyes Belhay", "Communauté, vidéos et lives uniquement selon les éléments configurés dans l’offre actuelle"],
    faqs: [faq("Faut-il déjà avoir une boutique ?", "Non, le programme couvre la niche, la recherche produit, la boutique et les campagnes."), faq("Le sourcing depuis la Chine est-il un conseil juridique ?", "Non, le module présente des principes de sourcing et ne remplace pas un conseil juridique ou douanier."), faq("L’accompagnement continue-t-il après la formation ?", "Les ressources et modalités d’accompagnement sont celles configurées dans l’offre actuelle ; elles sont précisées lors de l’inscription.")],
  },
};

const ar: Record<string, DetailedCourseContent> = {
  "formation-de-formateurs-tot": { presentation: "تكوين مكثف موجّه للراغبين في تطوير مهارات التنشيط والتواصل وتصميم الدورات. يرافقك البرنامج من إعداد الدورة إلى تنشيطها أمام مجموعة، مع تركيز كبير على التطبيق.", objectives: ["هيكلة دورة تدريبية مهنية", "تحديد احتياجات المشاركين", "صياغة أهداف تعليمية واضحة", "تحسين التحدث أمام الجمهور", "تطوير الثقة بالنفس", "إتقان أساسيات تواصل المدرب", "تسيير المجموعة والمواقف المختلفة", "استخدام التواصل اللفظي وغير اللفظي", "إعداد الوسائل وحقيبة المدرب", "بناء منهجية تنشيط عملية"], modules: fr["formation-de-formateurs-tot"].modules.map((item, i) => { const titles = ["مهنة المدرب", "تحليل الاحتياجات", "الأهداف التعليمية", "تصميم الدورة", "منهجية التدريب", "التحدث أمام الجمهور", "التواصل ولغة الجسد", "تسيير المجموعة", "تسيير الوقت", "مدخل إلى البرمجة اللغوية العصبية", "حقيبة المدرب", "تطبيق عملي"]; return { title: `الوحدة ${String(i + 1).padStart(2, "0")} — ${titles[i]}`, description: ["فهم مكانة المدرب ومسؤولياته.", "الانطلاق من الاحتياج الحقيقي لبناء مسار مفيد.", "تحويل الاحتياج إلى أهداف قابلة للملاحظة.", "بناء خطة واضحة وحصة منسجمة.", "اختيار أساليب تشجع المشاركة.", "تطوير حضور واضح ومقنع.", "تنسيق التواصل اللفظي وغير اللفظي.", "خلق إطار تفاعلي وإدارة المواقف الصعبة.", "تسيير الحصص والحفاظ على الإيقاع.", "اكتشاف مبادئ تواصل مفيدة في التدريب.", "إعداد الوسائل والتنظيم بطريقة موثوقة.", "تنفيذ دورة مصغرة والتطور عبر التغذية الراجعة."][i], lessons: item.lessons.map((lesson) => lesson.replace(/^[^·]+·\s*/, "").trim()) }; }), skills: ["تصميم دورة تدريبية", "تنشيط مجموعة", "التحدث بثقة", "إعداد وسائل بيداغوجية", "تسيير الوقت والتفاعل"], audience: ["المدربون المستقبليون", "المهنيون والاستشاريون", "المدربون الشخصيون والمسيرون", "الخبراء الراغبون في نقل خبرتهم"], methodology: ["محتوى منظم", "تمارين ومحاكاة", "تطبيقات أمام المجموعة", "تغذية راجعة وتحسين تدريجي"], practicalInfo: ["أكثر من 30 ساعة من التدريب المكثف", "حضوري", "بتأطير Djebbour Mohamed", "التاريخ والمكان حسب الدورة المبرمجة"], certification: "الشهادات المعروضة مرتبطة بالإعداد الحالي للمسار. أما أي اعتماد اختياري فيبقى خاضعًا للشروط التي تحددها الأكاديمية.", faqs: [faq("لمن يوجه هذا التكوين؟", "للمدربين المستقبليين والمهنيين الراغبين في نقل خبرتهم بطريقة أفضل."), faq("هل التكوين تطبيقي؟", "نعم، يجمع بين التمارين والمحاكاة والتطبيقات المهنية."), faq("هل الاعتماد الدولي مضمّن؟", "لا يتم اعتباره مضمّنًا دون تأكيد خاص؛ يرجى الاستفسار عن تفاصيل الدورة.")] },
  "agent-de-voyage": { presentation: "تكوين عملي للراغبين في اكتشاف طريقة عمل وكالة سفر واكتساب المهارات الأساسية للمهنة، من علاقة الزبون إلى تصميم المنتجات السياحية.", objectives: ["فهم طريقة عمل وكالة السفر", "اكتشاف الإطار التنظيمي للقطاع", "فهم المنتجات السياحية الأساسية", "تطوير تقنيات البيع", "فهم مبادئ التسعير", "التعرف على الأدوات المهنية", "تطوير مقاربة تجارية وتسويقية"], modules: ["مقدمة في مهنة وكيل السفر", "إنشاء وتسيير وكالة", "التنظيم والبيئة السياحية", "المنتجات السياحية", "الحجز والتسعير", "الأدوات المهنية ومدخل إلى Amadeus", "البيع والتسويق السياحي"].map((title, i) => ({ title: `الوحدة ${String(i + 1).padStart(2, "0")} — ${title}`, description: ["اكتشاف مهام الوكيل وتنظيم الوكالة والقطاع.", "هيكلة العمليات اليومية للوكالة.", "التعرف على المرجعيات والمسؤوليات المهنية.", "فهم عروض السفر وتقديمها.", "اكتساب مبادئ القراءة والتسعير.", "اكتشاف منطق أنظمة الحجز دون ادعاء شهادة رسمية.", "تحويل حاجة الزبون إلى عرض واضح."][i], lessons: fr["agent-de-voyage"].modules[i].lessons })), skills: ["استقبال الزبون ونصحه", "تقديم عرض سياحي", "قراءة معلومات الحجز", "بناء عرض تجاري", "المساهمة في تسيير وكالة"], audience: ["مهنيّو السياحة", "مسؤولو وموظفو الوكالات", "الراغبون في إنشاء وكالة", "المبتدئون المهتمون بالسفر"], methodology: ["دراسات حالة", "عروض وتمارين", "محاكاة علاقة الزبون", "تبادل الخبرات"], practicalInfo: ["حوالي 30 ساعة حسب الدورة", "خمسة أيام مكثفة حسب البرمجة", "حضوري", "بتأطير Amina Mghizili"], certification: "تظهر شهادة تكوين مهني ضمن الإعداد الحالي للمسار. ولا يتم ادعاء شهادة رسمية للأدوات دون تأكيد مستقل.", faqs: [faq("لمن يوجه المسار؟", "للمهنيين في السياحة ولكل من يرغب في اكتشاف أو تطوير نشاط وكالة سفر."), faq("هل توجد شهادة Amadeus رسمية؟", "البرنامج يقدم مدخلًا إلى منطق أدوات الحجز، ولا يدعي شهادة رسمية من Amadeus."), faq("ما هي المنهجية؟", "تجمع بين التطبيق ودراسات الحالة والمحاكاة وتبادل الخبرات.")] },
  photographie: { presentation: "تكوين مكثف وعملي لفهم أساسيات التصوير والتدرج من التقاط الصورة إلى معالجتها.", objectives: ["فهم الكاميرا وإعداداتها", "إتقان مثلث التعريض", "تحسين التركيز والحدة", "بناء تركيب متوازن", "استخدام الضوء الطبيعي والاصطناعي", "التصوير في الاستوديو والميدان", "اكتشاف سير عمل المعالجة", "تنظيم نشاط في مجال التصوير"], modules: ["فهم الكاميرا", "مثلث التعريض", "التركيز والحدة", "التركيب الفوتوغرافي", "الضوء", "التصوير في الاستوديو", "تصوير المنتجات", "التصوير الخارجي", "المعالجة ب Photoshop", "الذكاء الاصطناعي والتصوير", "تحويل التصوير إلى نشاط"].map((title, i) => ({ title: `الوحدة ${String(i + 1).padStart(2, "0")} — ${title}`, description: ["التعرف على المعدات والإعدادات الأساسية.", "فهم التوازن بين الفتحة والسرعة وISO.", "التحكم في الحدة حسب الموضوع.", "بناء صورة واضحة ومعبرة.", "قراءة الضوء وتوجيهه.", "تنصيب المشهد والتطبيق بإضاءة مضبوطة.", "إنتاج صور مناسبة للتجارة الإلكترونية والشبكات.", "التحضير للخروج والتكوين في الواقع.", "اعتماد سير عمل للتصحيحات الأساسية.", "اكتشاف أدوات مفيدة لتحسين سير العمل.", "عرض العمل وبناء أساس لخدمة تصوير."][i], lessons: fr.photographie.modules[i].lessons })), skills: ["ضبط الكاميرا", "التعريض والتركيب", "التصوير في الاستوديو والميدان", "معالجة الصورة", "تقديم خدمة تصوير"], audience: ["المبتدئون", "صناع المحتوى", "أصحاب المشاريع", "المصورون الراغبون في تنظيم ممارستهم"], methodology: ["عروض تطبيقية", "تمارين في الاستوديو", "خرجات تطبيقية حسب الدورة", "تحليل الصور والملاحظات"], practicalInfo: ["4 أيام مكثفة", "09:00–12:00 ثم 13:00–16:00", "استوديو مجهز حسب الدورة", "خرجتان تطبيقيتان عند برمجتهما", "بتأطير Toufik Derdour"], faqs: [faq("هل يناسب التكوين المبتدئين؟", "نعم، يبدأ من الأساسيات ويتدرج نحو التطبيق وسير العمل."), faq("هل التطبيق مبرمج؟", "نعم، يتضمن تمارين في الاستوديو وخرجات عندما تكون مبرمجة."), faq("ما هو التوقيت؟", "التوقيت المقترح من 09:00 إلى 12:00 ثم من 13:00 إلى 16:00.")] },
  "educatrice-enfants-gerante-creche": { presentation: "مسار عملي 5 في 1 لتطوير مهارات متكاملة في الطفولة المبكرة، من مرافقة الطفل إلى تنظيم مؤسسة الاستقبال.", objectives: ["فهم حاجات الطفل الأساسية", "مرافقة النمو الحركي والمعرفي والعاطفي", "تنظيم أنشطة مناسبة للعمر", "تسيير مجموعة أطفال", "إعداد أنشطة ما قبل التمدرس", "اكتشاف مبادئ مونتيسوري وغلين دومان", "تنظيم يوميات الحضانة", "التواصل مع الأولياء"], modules: ["مدخل إلى الطفولة المبكرة", "نمو الطفل", "تسيير مجموعة أطفال", "الأنشطة التربوية", "التحضيري وما قبل التمدرس", "مونتيسوري", "غلين دومان", "تسيير الحضانة", "تطبيق عملي"].map((title, i) => ({ title: `الوحدة ${String(i + 1).padStart(2, "0")} — ${title}`, description: ["تحديد إطار المهنة والمسؤولية.", "ملاحظة أبعاد نمو الطفل.", "خلق إطار آمن ومنظم.", "تصميم ورشات تنمي اليقظة والإبداع.", "مرافقة التعلمات الأولى حسب العمر.", "اكتشاف الاستقلالية والتعلم بالنشاط.", "عرض المبادئ والأنشطة المناسبة.", "تنظيم العمليات والعلاقة مع الأولياء.", "ربط المعارف بمواقف مهنية."][i], lessons: fr["educatrice-enfants-gerante-creche"].modules[i].lessons })), skills: ["مرافقة الطفل", "إعداد أنشطة تربوية", "تسيير مجموعة", "تنظيم مؤسسة استقبال", "التواصل مع الأولياء"], audience: ["المربيات والمنشطات", "مسؤولو الحضانات", "معلمات التحضيري وما قبل التمدرس", "الراغبون في العمل مع الأطفال"], methodology: ["مرجعيات تربوية منظمة", "ورشات وحالات تطبيقية", "إعداد أنشطة", "محاكاة مواقف مهنية"], practicalInfo: ["4 أيام مكثفة", "09:00–15:00", "مسار بخمسة محاور متكاملة", "بتأطير Safa Belkharchouche"], faqs: [faq("ماذا يعني 5 في 1؟", "يشمل المسار التربية في الحضانة وتسيير الحديقة والتمهيدي ومونتيسوري وغلين دومان."), faq("ما هو التوقيت؟", "المدة المقترحة أربعة أيام مكثفة من 09:00 إلى 15:00."), faq("هل التكوين تطبيقي؟", "نعم، يجمع بين المعارف التربوية وإعداد الأنشطة والمحاكاة.")] },
  "ecommerce-marketing-digital": { presentation: "تكوين عملي لتعلم بناء وتطوير مشروع تجارة إلكترونية مناسب للسوق الجزائري، من اختيار السوق إلى اكتساب الزبائن وتحليل الحملات الإعلانية.", objectives: ["فهم أساسيات التجارة الإلكترونية", "اختيار مجال وفرصة مناسبة", "البحث عن المنتجات والموردين", "بناء عرض ومتجر", "إنشاء محتوى إعلاني", "إطلاق حملات Meta وTikTok", "قراءة النتائج والتحسين", "استخدام الذكاء الاصطناعي كمساعد تسويقي", "تنظيم العمليات وعلاقة الزبون"], modules: ["أساسيات التجارة الإلكترونية", "اختيار المجال", "البحث عن المنتجات", "التوريد من الجزائر", "التوريد والاستيراد من الصين", "بناء العلامة", "المحتوى الإعلاني", "إنشاء وتحسين المتجر", "إعلانات Facebook وInstagram", "إعلانات TikTok", "تحليل الأداء", "التوسع", "الذكاء الاصطناعي للتجارة", "التنظيم العملياتي"].map((title, i) => ({ title: `الوحدة ${String(i + 1).padStart(2, "0")} — ${title}`, description: ["فهم النموذج وتنظيم المشروع.", "تحليل الطلب والمنافسة والتموقع.", "تقييم المنتج قبل بناء العرض.", "تنظيم البحث عن موردين محليين.", "اكتشاف مبادئ التوريد الدولي دون تقديم استشارة قانونية أو جمركية.", "بناء صورة علامة مميزة.", "تحويل العرض إلى محتوى إعلاني.", "بناء تجربة واضحة ومطمئنة على الهاتف.", "إطلاق واختبار وقراءة الحملات.", "تكييف المحتوى والحملات مع TikTok.", "اتخاذ القرارات اعتمادًا على المؤشرات.", "تطوير الحملة تدريجيًا.", "استخدام الذكاء الاصطناعي في البحث والإنتاجية.", "تنظيم الطلب والتوصيل وعلاقة الزبون."][i], lessons: fr["ecommerce-marketing-digital"].modules[i]?.lessons ?? [] })), skills: ["تحليل السوق", "اختيار المنتج", "بناء متجر", "إنشاء محتوى إعلاني", "إطلاق وقراءة الحملات", "تحسين العرض"], audience: ["المبتدئون", "أصحاب المشاريع", "البائعون عبر الإنترنت", "الراغبون في إطلاق أو تنظيم نشاط إلكتروني"], methodology: ["أكثر من 30 ساعة تطبيقية", "عروض وورشات", "حالات مرتبطة بالسوق", "متابعة وموارد حسب العرض الحالي"], practicalInfo: ["مسار موزع على حوالي شهر", "حضوري مع موارد عبر الإنترنت", "بتأطير Ilyes Belhay", "المجتمع والفيديوهات واللقاءات حسب العناصر المفعلة في العرض"], faqs: [faq("هل يجب أن أملك متجرًا؟", "لا، يغطي البرنامج المجال والمنتج والمتجر والحملات."), faq("هل التوريد من الصين استشارة قانونية؟", "لا، يقدم المحور مبادئ عامة ولا يعوض استشارة قانونية أو جمركية."), faq("هل توجد مرافقة بعد التكوين؟", "تخضع الموارد والمرافقة لما هو مفعّل في العرض الحالي ويتم توضيحه عند التسجيل.")] },
};

export const localizedCourseContent: Record<string, { fr: DetailedCourseContent; ar: DetailedCourseContent }> = Object.fromEntries(Object.keys(fr).map((slug) => [slug, { fr: fr[slug], ar: ar[slug] }])) as Record<string, { fr: DetailedCourseContent; ar: DetailedCourseContent }>;

export function getDetailedCourseContent(slug: string, locale: "fr" | "ar" = "fr") {
  return localizedCourseContent[slug]?.[locale] ?? null;
}
