export const locales = ["fr", "ar"] as const;
export type Locale = (typeof locales)[number];
export const isLocale = (value: string): value is Locale => locales.includes(value as Locale);
export const localeLabels: Record<Locale, string> = { fr: "FR", ar: "العربية" };

export const t = {
  fr: {
    navCourses: "Formations", navTrainers: "Formateurs", navJoin: "Rejoignez-nous", navJoinLink: "Devenir formateur", navAbout: "À propos", navContact: "Contact", navCta: "Voir les formations",
    homeEyebrow: "ELIVA SCHOOL / apprendre autrement", homeTitle: "Les compétences qui créent de vraies opportunités.", homeLead: "Des formations pratiques, des formateurs de terrain et un accompagnement conçu pour passer de la théorie à l’action.", discover: "Découvrir les formations", register: "S’inscrire",
    coursesEyebrow: "Les parcours ELIVA", coursesTitle: "Des formations pour passer de l’intention à la pratique.", coursesLead: "Choisissez une compétence, rencontrez son expert et découvrez un format pensé pour votre prochain mouvement professionnel.", viewCourse: "Voir la formation",
    trainersEyebrow: "L’expertise en action", trainersTitle: "Des professionnels qui savent transmettre.", trainersLead: "Chaque parcours est porté par une personne qui pratique son métier et transforme son expérience en méthodes utiles.", viewProfile: "Voir le profil",
    duration: "Durée", mode: "Mode", trainer: "Formateur", program: "Programme", learn: "Ce que vous allez apprendre", faq: "Questions fréquentes", contact: "Parlons de votre projet.", registration: "Inscription", submitRegistration: "Envoyer ma demande d’inscription", fullName: "Nom et prénom", phone: "Téléphone / WhatsApp", email: "E-mail", wilaya: "Wilaya", message: "Message / remarque", consent: "J’accepte d’être contacté(e) au sujet de ma demande.", choose: "Choisir", presentiel: "Présentiel", online: "En ligne",
    recruitmentTitle: "Vous avez une expertise ? Transmettez-la avec ELIVA SCHOOL.", recruitmentLead: "Nous recherchons des formateurs, experts métier et professionnels de terrain capables de transformer leur expérience en formations pratiques et à fort impact.", apply: "Déposer ma candidature", step: "Étape", next: "Continuer", previous: "Retour", submitApplication: "Envoyer ma candidature", cv: "CV PDF", success: "Candidature envoyée avec succès.", home: "Retour à l’accueil", required: "Ce champ est obligatoire.", error: "Une erreur est survenue. Réessayez plus tard.", noDates: "Dates et lieux à confirmer.",
    trust: ["Formations pratiques", "Experts métier", "Suivi personnalisé", "Présentiel & digital"], editorialLabel: "Apprendre autrement", editorialTitle: "La compétence prend de la valeur lorsqu’elle devient action.", editorialBody: "Une pédagogie claire, des méthodes de terrain et un cadre pensé pour vous aider à progresser avec confiance.", methodologyLabel: "Notre méthode", methodologyTitle: "Un apprentissage qui vous accompagne jusqu’au prochain mouvement.", methodology: [{ title: "Comprendre", body: "Des contenus structurés pour donner du sens à chaque étape." }, { title: "Pratiquer", body: "Des exercices, cas et situations proches de la réalité professionnelle." }, { title: "Avancer", body: "Un accompagnement qui vous aide à transformer l’acquis en projet." }], finalTitle: "Prêt à passer à l’étape suivante ?", finalBody: "Choisissez le parcours qui correspond à votre objectif.", contactCta: "Nous contacter"
  },
  ar: {
    navCourses: "الدورات التدريبية", navTrainers: "مدربونا", navJoin: "انضم إلينا", navJoinLink: "انضم إلينا كمدرب", navAbout: "من نحن", navContact: "تواصل معنا", navCta: "اكتشف الدورات",
    homeEyebrow: "ELIVA SCHOOL / نتعلم بطريقة مختلفة", homeTitle: "مهارات تصنع فرصًا حقيقية.", homeLead: "دورات عملية، مدربون من الميدان ومرافقة تساعدك على الانتقال من النظرية إلى التطبيق.", discover: "اكتشف الدورات", register: "سجّل الآن",
    coursesEyebrow: "مسارات ELIVA", coursesTitle: "دورات تنقلك من الرغبة إلى التطبيق.", coursesLead: "اختر مهارة، تعرّف على خبيرها واكتشف مسارًا مناسبًا لخطوتك المهنية القادمة.", viewCourse: "اكتشف الدورة",
    trainersEyebrow: "الخبرة في خدمة التعلم", trainersTitle: "متخصصون يعرفون كيف ينقلون خبرتهم.", trainersLead: "يقود كل مسار شخص يمارس مهنته ويحوّل خبرته إلى أساليب مفيدة.", viewProfile: "عرض الملف",
    duration: "المدة", mode: "النمط", trainer: "المدرب", program: "البرنامج", learn: "ما ستتعلمه", faq: "الأسئلة الشائعة", contact: "لنتحدث عن مشروعك.", registration: "التسجيل", submitRegistration: "إرسال طلب التسجيل", fullName: "الاسم واللقب", phone: "الهاتف / واتساب", email: "البريد الإلكتروني", wilaya: "الولاية", message: "ملاحظات", consent: "أوافق على التواصل معي بخصوص طلبي.", choose: "اختر", presentiel: "حضوري", online: "عن بُعد",
    recruitmentTitle: "لديك خبرة؟ انقلها مع ELIVA SCHOOL.", recruitmentLead: "نبحث عن مدربين وخبراء مهنيين قادرين على تحويل خبرتهم إلى دورات عملية مؤثرة.", apply: "أرسل ترشحك", step: "الخطوة", next: "متابعة", previous: "رجوع", submitApplication: "إرسال الترشح", cv: "السيرة الذاتية PDF", success: "تم إرسال ترشحك بنجاح.", home: "العودة إلى الرئيسية", required: "هذا الحقل إجباري.", error: "حدث خطأ. حاول مرة أخرى لاحقًا.", noDates: "سيتم تحديد التواريخ والأماكن لاحقًا.",
    trust: ["دورات عملية", "خبراء من الميدان", "مرافقة شخصية", "حضوري وعن بُعد"], editorialLabel: "نتعلم بطريقة مختلفة", editorialTitle: "تزداد قيمة المهارة عندما تتحول إلى فعل.", editorialBody: "منهجية واضحة، تطبيقات ميدانية وإطار يساعدك على التقدم بثقة.", methodologyLabel: "منهجيتنا", methodologyTitle: "تعلم يرافقك نحو خطوتك المهنية القادمة.", methodology: [{ title: "افهم", body: "محتوى منظم يمنح معنى لكل مرحلة." }, { title: "طبّق", body: "تمارين ودراسات حالة قريبة من الواقع المهني." }, { title: "تقدّم", body: "مرافقة تساعدك على تحويل التعلم إلى مشروع." }], finalTitle: "مستعد للخطوة التالية؟", finalBody: "اختر المسار المناسب لهدفك.", contactCta: "تواصل معنا"
  }
} as const;

export function localizePath(path: string, from: Locale, to: Locale) {
  const parts = path.split("?");
  const raw = parts[0];
  const clean = raw === "/" + from ? "/" : raw.startsWith("/" + from + "/") ? raw.slice(from.length + 1) : raw;
  return "/" + to + clean + (parts[1] ? "?" + parts[1] : "");
}

export const localizedCourse: Record<string, Record<Locale, { title: string; category: string; promise: string; benefits: string[] }>> = {
  "formation-de-formateurs-tot": { fr: { title: "Formation de Formateurs — TOT", category: "Formation de formateurs", promise: "Apprenez à concevoir, structurer et animer une formation professionnelle avec une approche pratique.", benefits: ["Pratique intensive", "Méthodologies applicables", "5 certificats inclus"] }, ar: { title: "تكوين المدربين — TOT", category: "تكوين المدربين", promise: "تعلّم تصميم وتنظيم وتنشيط دورة تدريبية مهنية بمنهج عملي.", benefits: ["تطبيق مكثف", "منهجيات قابلة للتطبيق", "5 شهادات مضمّنة"] } },
  "agent-de-voyage": { fr: { title: "Agent de Voyage & Gestion d’Agence", category: "Métiers & tourisme", promise: "Maîtrisez les fondamentaux opérationnels, commerciaux et administratifs d’une agence de voyage.", benefits: ["Études de cas", "Simulations professionnelles", "Formation pratique"] }, ar: { title: "وكيل سفر وتسيير وكالة", category: "السياحة والمهن", promise: "أتقن الأساسيات العملية والتجارية والإدارية لتسيير وكالة سفر.", benefits: ["دراسات حالة", "محاكاة مهنية", "تكوين عملي"] } },
  photographie: { fr: { title: "Formation Professionnelle en Photographie", category: "Création & image", promise: "De débutant à photographe prêt à pratiquer.", benefits: ["Studio équipé", "Deux sorties pratiques", "Photoshop & IA"] }, ar: { title: "التكوين المهني في التصوير", category: "الإبداع والصورة", promise: "انتقل من المبتدئ إلى مصور مستعد للممارسة.", benefits: ["استوديو مجهز", "خرجتان تطبيقيتان", "فوتوشوب والذكاء الاصطناعي"] } },
  "educatrice-enfants-gerante-creche": { fr: { title: "Petite Enfance — Formation 5 en 1", category: "Petite enfance", promise: "Un parcours pratique pour développer cinq compétences complémentaires dans la petite enfance.", benefits: ["5 formations en 1", "Pratique pédagogique", "Accompagnement de l’enfant"] }, ar: { title: "الطفولة المبكرة — 5 تكوينات في تكوين واحد", category: "الطفولة المبكرة", promise: "مسار عملي لتطوير خمس مهارات متكاملة في مجال الطفولة المبكرة.", benefits: ["5 تكوينات في واحد", "تطبيق تربوي", "مرافقة الطفل"] } },
  "ecommerce-marketing-digital": { fr: { title: "E-commerce & Digital Marketing", category: "Business & e-commerce", promise: "Construisez, lancez et développez votre activité e-commerce de A à Z.", benefits: ["Plus de 30 heures de pratique", "Ressources et vidéos", "Accompagnement au lancement"] }, ar: { title: "التجارة الإلكترونية والتسويق الرقمي", category: "الأعمال والتجارة الإلكترونية", promise: "أنشئ وأطلق وطوّر نشاطك في التجارة الإلكترونية من الألف إلى الياء.", benefits: ["أكثر من 30 ساعة تطبيقية", "موارد وفيديوهات", "مرافقة عند الإطلاق"] } }
};
