import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { isLocale, t } from "@/lib/i18n";
import { LocaleNavbar } from "@/components/i18n/locale-navbar";
import { LocaleFooter } from "@/components/i18n/locale-footer";
import { LocalizedRecruitmentForm } from "@/components/i18n/localized-recruitment-form";

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  if (!isLocale(locale)) return {};
  return { title: `${t[locale].navJoinLink} | Meritify Academy`, description: t[locale].recruitmentLead, alternates: { canonical: `/${locale}/rejoignez-nous/formateur`, languages: { fr: "/fr/rejoignez-nous/formateur", ar: "/ar/rejoignez-nous/formateur" } } };
}

const content = {
  fr: {
    badge: "🎓 Réseau de formateurs Meritify Academy", title: "Partagez votre expertise. Créez de l’impact. Rejoignez Meritify.", lead: "Vous maîtrisez votre domaine et souhaitez transmettre votre expertise à travers une expérience de formation professionnelle ? Rejoignez le réseau de formateurs Meritify Academy.", apply: "🚀 Déposer ma candidature", discover: "✨ Découvrir Meritify", trust: ["🎓 Expertises variées", "🤝 Collaboration professionnelle", "📍 Opportunités dans plusieurs wilayas", "💻 Présentiel & en ligne"], whyEyebrow: "Notre réseau", whyTitle: "✨ Pourquoi rejoindre Meritify Academy ?", whyLead: "Nous recherchons des formateurs qui ne se contentent pas de transmettre des informations, mais qui créent une véritable expérience d’apprentissage.",
    benefits: [["🤝", "Opportunités de collaboration", "Participez à des formations et programmes selon votre spécialité et les besoins des apprenants."], ["📍", "Un réseau qui s’étend", "Intervenez à Skikda et dans d’autres wilayas selon la programmation."], ["💻", "Présentiel & en ligne", "Contribuez à des programmes en salle ou à distance selon la nature de la formation."], ["📣", "Soutien à la promotion", "Les formations sont organisées et valorisées au sein de l’écosystème Meritify, selon le programme convenu."], ["🎯", "L’expertise avant tout", "Nous nous intéressons à ce que vous êtes capable d’apporter concrètement aux participants."], ["🌱", "Une relation durable", "Construisons une collaboration professionnelle appelée à évoluer avec les bons profils."]],
    profileEyebrow: "Le bon profil", profileTitle: "🎯 Êtes-vous le formateur que nous recherchons ?", profileLead: "Nous souhaitons rencontrer des professionnels de terrain capables de simplifier leur savoir et de le transformer en une expérience utile.", checklist: ["Une expérience réelle dans votre spécialité", "Une bonne capacité de communication", "Le goût d’expliquer et de simplifier", "Fiabilité et professionnalisme", "Un contenu pédagogique structuré", "L’envie de progresser et de collaborer", "La disponibilité en présentiel ou à distance selon le programme"], domainsEyebrow: "Votre terrain d’expertise", domainsTitle: "🧩 Des domaines, une même exigence de transmission", domainsLead: "Ces exemples illustrent les expertises que nous pouvons accueillir. Votre spécialité peut aussi trouver sa place dans le réseau.", domains: ["💼 Business & management", "📱 Marketing digital", "🛒 E-commerce", "💻 Technologie & digital", "🎨 Design & créativité", "📷 Photographie & contenu", "✈️ Tourisme & voyage", "🧠 Soft skills", "👶 Éducation & petite enfance", "📊 Gestion", "🗣️ Communication", "➕ Autres spécialités"], howEyebrow: "Un parcours simple", howTitle: "🚀 Comment rejoindre le réseau ?", steps: [["01", "📝 Envoyez votre candidature", "Remplissez le formulaire et partagez vos informations professionnelles."], ["02", "📄 Étude du profil", "L’équipe Meritify étudie votre expérience, votre spécialité et votre CV."], ["03", "🤝 Échange professionnel", "Si votre profil correspond, nous vous contactons pour découvrir votre approche et votre programme."], ["04", "🎓 Collaboration", "Après accord, vous pouvez rejoindre le réseau et les programmes adaptés."]], formEyebrow: "Votre prochaine étape", formTitle: "🚀 Commencez votre candidature", formLead: "Trois étapes simples pour nous permettre de découvrir votre expertise.", finalTitle: "🎓 Votre expertise mérite d’être transmise.", finalLead: "Si vous êtes prêt à partager vos connaissances et à créer une expérience de formation utile, Meritify Academy peut être votre prochaine étape.", finalCta: "🚀 Déposer ma candidature"
  },
  ar: {
    badge: "🎓 شبكة مدربي Meritify Academy", title: "شارك خبرتك. اصنع أثرًا. وانضم إلى مدربي Meritify.", lead: "إذا كنت تمتلك خبرة حقيقية في مجالك وتستطيع تحويل معرفتك إلى تجربة تدريبية عملية، نريد أن نتعرف عليك. انضم إلى شبكة مدربي Meritify Academy وساهم في تقديم تجارب تدريبية احترافية للمتعلمين في مختلف المجالات.", apply: "🚀 قدّم طلب الانضمام", discover: "✨ اكتشف Meritify", trust: ["🎓 خبرات متنوعة", "🤝 تعاون احترافي", "📍 فرص تدريب في عدة ولايات", "💻 حضوري وعن بُعد"], whyEyebrow: "شبكتنا", whyTitle: "✨ لماذا تنضم إلى Meritify Academy؟", whyLead: "نبحث عن مدربين لا يكتفون بنقل المعلومات، بل يصنعون تجربة تعليمية حقيقية.",
    benefits: [["🤝", "فرص تعاون", "فرص للمشاركة في دورات وبرامج تدريبية حسب التخصص والحاجة."], ["📍", "الوصول إلى ولايات مختلفة", "إمكانية تنظيم دورات في سكيكدة وولايات أخرى حسب البرنامج."], ["💻", "حضوري وعن بُعد", "إمكانية المشاركة في برامج حضورية أو رقمية حسب طبيعة الدورة."], ["📣", "دعم في الترويج", "تنظيم وتسويق الدورات ضمن منظومة Meritify Academy عند الاتفاق على البرنامج."], ["🎯", "التركيز على الخبرة", "نهتم بما تستطيع تقديمه فعليًا للمتدرب."], ["🌱", "بناء علاقة طويلة المدى", "نبحث عن تعاون مهني قابل للتطور مع المدربين المناسبين."]],
    profileEyebrow: "المدرب الذي نبحث عنه", profileTitle: "🎯 هل أنت المدرب الذي نبحث عنه؟", profileLead: "نرغب في التعرف على أصحاب الخبرة العملية الذين يمتلكون القدرة على تبسيط المعرفة وتحويلها إلى تجربة تدريبية مفيدة.", checklist: ["خبرة حقيقية في تخصصك", "قدرة جيدة على التواصل", "مهارة في الشرح وتبسيط المعلومات", "الالتزام والاحترافية", "محتوى تدريبي منظم", "الرغبة في التطور والتعاون", "الاستعداد للتدريب الحضوري أو عن بُعد حسب البرنامج"], domainsEyebrow: "مجال خبرتك", domainsTitle: "🧩 مجالات تدريب متعددة بروح واحدة", domainsLead: "هذه أمثلة على المجالات التي يمكن أن تستقبلها الشبكة. تخصصك يمكن أن يجد مكانه أيضًا ضمن Meritify.", domains: ["💼 الأعمال والإدارة", "📱 التسويق الرقمي", "🛒 التجارة الإلكترونية", "💻 التكنولوجيا والرقمنة", "🎨 التصميم والإبداع", "📷 التصوير وصناعة المحتوى", "✈️ السياحة والسفر", "🧠 المهارات الشخصية", "👶 التربية والطفولة", "📊 الإدارة والتسيير", "🗣️ التواصل", "➕ تخصصات أخرى"], howEyebrow: "مسار واضح", howTitle: "🚀 كيف تنضم إلى شبكة المدربين؟", steps: [["01", "📝 أرسل طلبك", "املأ استمارة الانضمام وأرسل معلوماتك المهنية."], ["02", "📄 نراجع ملفك", "يقوم فريق Meritify بمراجعة خبرتك وتخصصك والسيرة الذاتية."], ["03", "🤝 جلسة تعارف", "إذا كان ملفك مناسبًا، نتواصل معك للتعرف على برنامجك وطريقتك في التدريب."], ["04", "🎓 نبدأ التعاون", "عند الاتفاق، يمكن إدراجك ضمن شبكة المدربين والبرامج المناسبة."]], formEyebrow: "خطوتك القادمة", formTitle: "🚀 ابدأ طلب الانضمام", formLead: "ثلاث خطوات بسيطة تفصلنا عن التعرف على خبرتك.", finalTitle: "🎓 خبرتك تستحق أن تصل إلى الآخرين.", finalLead: "إذا كنت مستعدًا لمشاركة معرفتك وصناعة تجربة تدريبية ذات قيمة، فقد تكون Meritify Academy محطتك القادمة.", finalCta: "🚀 قدّم طلبك الآن"
  }
} as const;

export default async function Recruit({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  if (!isLocale(locale)) notFound();
  const c = content[locale]; const rtl = locale === "ar";
  return <main dir={rtl ? "rtl" : "ltr"}>
    <LocaleNavbar locale={locale} path={`/${locale}/rejoignez-nous/formateur`} />
    <section className="relative overflow-hidden bg-ink py-20 text-white sm:py-28"><div className="pointer-events-none absolute -end-24 -top-24 size-80 rounded-full border border-gold/20 opacity-70" /><div className="section-shell relative grid items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><div className="motion-reveal"><p className="eyebrow text-gold">{c.badge}</p><h1 className="mt-6 max-w-3xl text-5xl font-semibold leading-[.98] tracking-[-.055em] sm:text-7xl">{c.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/70">{c.lead}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#candidature" className="inline-flex min-h-12 items-center justify-center rounded-full bg-gold px-6 font-semibold text-ink transition hover:bg-white">{c.apply} <span className="ms-2" aria-hidden>↗</span></a><a href="#pourquoi" className="inline-flex min-h-12 items-center justify-center rounded-full border border-white/25 px-6 font-semibold text-white transition hover:border-gold hover:text-gold">{c.discover}</a></div></div><div className="relative min-h-[360px] motion-reveal motion-reveal-delay-2" aria-label={rtl ? "لمحة عن شبكة المدربين" : "Aperçu du réseau de formateurs"}><div className="absolute inset-8 rounded-[2rem] border border-gold/30 bg-white/[.04] shadow-[0_0_80px_rgba(202,151,44,.13)]" /><div className="absolute inset-x-12 top-14 rounded-3xl border border-white/15 bg-white/[.08] p-6 backdrop-blur-sm"><p className="eyebrow text-gold">{rtl ? "تجربة تدريبية ذات أثر" : "Une transmission qui compte"}</p><p className="mt-5 text-3xl font-semibold">{rtl ? "خبرة · معرفة · أثر" : "Expertise · Savoir · Impact"}</p><div className="mt-8 h-px bg-gold/40" /><div className="mt-5 grid grid-cols-3 gap-3 text-center text-xs text-white/65"><span>🎤<br />{rtl ? "تواصل" : "Expression"}</span><span>📚<br />{rtl ? "خبرة" : "Expertise"}</span><span>🎯<br />{rtl ? "أثر" : "Impact"}</span></div></div><span className="absolute start-2 top-20 rounded-full border border-gold/30 bg-ink px-4 py-3 text-sm text-gold shadow-xl">📚 {rtl ? "معرفة" : "Savoir"}</span><span className="absolute end-1 top-8 rounded-full border border-white/15 bg-ink px-4 py-3 text-sm text-white/80 shadow-xl">🎓 {rtl ? "تكوين" : "Formation"}</span><span className="absolute bottom-12 start-10 rounded-full border border-white/15 bg-ink px-4 py-3 text-sm text-white/80 shadow-xl">🤝 {rtl ? "تعاون" : "Partenariat"}</span><span className="absolute bottom-4 end-4 rounded-full border border-gold/30 bg-gold px-4 py-3 text-sm font-semibold text-ink shadow-xl">🚀 {rtl ? "انطلاقة" : "Élan"}</span></div></div></section>
    <section className="border-b border-ink/10 bg-sand py-6"><div className="section-shell grid gap-4 text-sm font-semibold text-ink/70 sm:grid-cols-2 lg:grid-cols-4">{c.trust.map((item) => <div key={item} className="border-ink/15 sm:border-s sm:px-5 first:border-0 first:px-0">{item}</div>)}</div></section>
    <section id="pourquoi" className="section-shell py-20 sm:py-28"><div className="max-w-3xl"><p className="eyebrow text-gold-dark">{c.whyEyebrow}</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-6xl">{c.whyTitle}</h2><p className="mt-6 text-lg leading-8 text-ink/65">{c.whyLead}</p></div><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{c.benefits.map(([icon, title, body]) => <article key={title} className="group rounded-3xl border border-ink/10 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-gold/50 hover:shadow-xl"><span className="text-3xl transition-transform group-hover:scale-110">{icon}</span><h3 className="mt-5 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-ink/60">{body}</p></article>)}</div></section>
    <section className="bg-sand py-20 sm:py-28"><div className="section-shell grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><p className="eyebrow text-gold-dark">{c.profileEyebrow}</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">{c.profileTitle}</h2><p className="mt-6 leading-8 text-ink/65">{c.profileLead}</p></div><div className="grid gap-3 sm:grid-cols-2">{c.checklist.map((item) => <div key={item} className="rounded-2xl border border-ink/10 bg-white p-4 text-sm font-semibold"><span className="me-2 text-gold-dark">✓</span>{item}</div>)}</div></div></section>
    <section className="section-shell py-20 sm:py-28"><div className="max-w-3xl"><p className="eyebrow text-gold-dark">{c.domainsEyebrow}</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">{c.domainsTitle}</h2><p className="mt-5 leading-8 text-ink/65">{c.domainsLead}</p></div><div className="mt-10 flex flex-wrap gap-3">{c.domains.map((domain) => <span key={domain} className="rounded-full border border-ink/15 bg-white px-5 py-3 text-sm font-semibold transition hover:border-gold hover:bg-gold/10">{domain}</span>)}</div></section>
    <section className="bg-ink py-20 text-white sm:py-28"><div className="section-shell"><p className="eyebrow text-gold">{c.howEyebrow}</p><h2 className="mt-4 text-4xl font-semibold sm:text-5xl">{c.howTitle}</h2><div className="relative mt-12 grid gap-5 md:grid-cols-4">{c.steps.map(([number, title, body]) => <article key={number} className="relative border-s border-gold/40 px-5 py-2 first:border-0 md:border-s md:first:border-s"><span className="text-sm font-semibold text-gold">{number}</span><h3 className="mt-4 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-7 text-white/60">{body}</p></article>)}</div></div></section>
    <section id="candidature" className="section-shell grid gap-12 py-20 sm:py-28 lg:grid-cols-[.75fr_1.25fr] lg:items-start"><div className="lg:sticky lg:top-28"><p className="eyebrow text-gold-dark">{c.formEyebrow}</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">{c.formTitle}</h2><p className="mt-6 leading-8 text-ink/65">{c.formLead}</p><div className="mt-8 rounded-2xl border border-gold/30 bg-gold/10 p-5 text-sm leading-7">📄 {rtl ? "السيرة الذاتية تبقى خاصة ويتم الاطلاع عليها فقط ضمن مسار دراسة الترشح." : "Votre CV reste privé et n’est consulté que dans le cadre de l’étude de votre candidature."}</div></div><LocalizedRecruitmentForm locale={locale} /></section>
    <section className="relative overflow-hidden bg-ink py-20 text-white sm:py-24"><div className="pointer-events-none absolute end-0 top-0 size-64 rounded-full bg-gold/10 blur-3xl" /><div className="section-shell relative flex flex-col justify-between gap-8 sm:flex-row sm:items-end"><div><h2 className="max-w-3xl text-4xl font-semibold sm:text-5xl">{c.finalTitle}</h2><p className="mt-5 max-w-2xl leading-8 text-white/65">{c.finalLead}</p></div><a href="#candidature" className="inline-flex min-h-12 shrink-0 items-center justify-center rounded-full bg-gold px-6 font-semibold text-ink hover:bg-white">{c.finalCta} ↗</a></div></section>
    <LocaleFooter locale={locale} />
  </main>;
}
