"use client";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";

const links = [{ href: "/admin", label: "Vue d’ensemble" }, { href: "/admin/inscriptions", label: "Inscriptions" }, { href: "/admin/formations", label: "Formations CMS" }, { href: "/admin/formateurs", label: "Formateurs CRM" }, { href: "/admin/formateurs/publics", label: "Formateurs publics" }, { href: "/admin/centres", label: "Centres & Salles" }];
export function AdminShell({ children, email }: { children: React.ReactNode; email?: string }) {
  const pathname = usePathname(); const router = useRouter(); const [open, setOpen] = useState(false);
  async function signOut() { await createClient().auth.signOut(); router.replace("/admin/login"); router.refresh(); }
  return <div className="min-h-screen bg-background text-ink"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-white/10 bg-ink px-4 text-white lg:hidden"><Link href="/admin" className="font-semibold tracking-[0.08em]">ELIVA <span className="text-gold">ADMIN</span></Link><button onClick={() => setOpen(value => !value)} className="rounded-lg border border-white/20 px-3 py-2 text-sm">Menu</button></header><aside className={(open ? "translate-x-0 " : "-translate-x-full ") + "fixed inset-y-0 left-0 z-40 w-72 border-r border-white/10 bg-ink p-6 text-white transition-transform lg:translate-x-0"}><div className="flex items-center justify-between"><Link href="/admin" className="font-semibold tracking-[0.08em]">ELIVA <span className="text-gold">ADMIN</span></Link><button onClick={() => setOpen(false)} className="text-white/50 lg:hidden" aria-label="Fermer">×</button></div><p className="mt-10 text-xs uppercase tracking-[0.18em] text-white/40">Espace privé</p><nav className="mt-4 grid gap-2">{links.map(link => <Link key={link.href} href={link.href} onClick={() => setOpen(false)} className={(pathname === link.href || pathname.startsWith(link.href + "/") ? "bg-gold text-ink " : "text-white/70 hover:bg-white/10 hover:text-white ") + "rounded-xl px-4 py-3 text-sm font-semibold transition"}>{link.label}</Link>)}</nav><div className="absolute inset-x-6 bottom-6 border-t border-white/10 pt-5"><p className="truncate text-xs text-white/45">{email}</p><button onClick={signOut} className="mt-3 text-sm font-semibold text-gold hover:text-white">Se déconnecter ↗</button></div></aside><main className="lg:pl-72"><div className="mx-auto max-w-[1440px] p-5 sm:p-8 lg:p-10">{children}</div></main></div>;
}
