"use client";

import { useMemo, useState } from "react";

type Course = { id: string; title: string | null; excerpt: string | null; cover_url?: string | null; slug?: string | null };
type ModuleItem = { id: string; title_fr: string | null; title_ar: string | null };
type LessonItem = { id: string; module_id: string; title_fr: string | null; title_ar: string | null; description_fr: string | null; description_ar: string | null; video_provider: string | null; video_url: string | null; module?: ModuleItem };
type LiveItem = { id: string; title_fr: string | null; title_ar: string | null; starts_at: string; join_url: string | null };
type ResourceItem = { id: string; title_fr: string | null; title_ar: string | null; signed_url?: string | null; external_url?: string | null };
type Props = { course: Course; modules: ModuleItem[]; lessons: LessonItem[]; lives: LiveItem[]; locale: "fr" | "ar" };

export default function StudentCoursePlayer({ modules, lessons, lives, locale }: Props) {
  const ar = locale === "ar";
  const ordered = useMemo(() => modules.flatMap((module) => lessons.filter((lesson) => lesson.module_id === module.id).map((lesson) => ({ ...lesson, module }))), [modules, lessons]);
  const [selectedId, setSelectedId] = useState(ordered[0]?.id);
  const [resources, setResources] = useState<ResourceItem[]>([]);
  const [open, setOpen] = useState(false);
  const selected = ordered.find((lesson) => lesson.id === selectedId) ?? ordered[0];
  async function select(id: string) { setSelectedId(id); setOpen(false); const response = await fetch(`/api/lms/resources?lessonId=${encodeURIComponent(id)}`); const data = await response.json().catch(() => ({})); setResources(response.ok ? data.resources ?? [] : []); }
  return <div className="mt-10 grid gap-6 lg:grid-cols-[300px_minmax(0,1fr)]">
    <button type="button" onClick={() => setOpen((value) => !value)} className="rounded-2xl border border-ink/10 bg-white p-4 text-start font-semibold lg:hidden">{ar ? "عرض الوحدات" : "Afficher le programme"} ☰</button>
    <aside className={`${open ? "block" : "hidden"} rounded-3xl border border-ink/10 bg-white p-4 lg:block`}><p className="px-3 py-2 text-xs font-semibold uppercase tracking-[0.14em] text-gold-dark">{ar ? "المنهج" : "Programme"}</p><div className="grid gap-2">{modules.map((module, index) => <div key={module.id}><p className="px-3 py-2 text-sm font-semibold">{index + 1}. {ar ? module.title_ar : module.title_fr}</p>{lessons.filter((lesson) => lesson.module_id === module.id).map((lesson) => <button type="button" key={lesson.id} onClick={() => select(lesson.id)} className={`${selected?.id === lesson.id ? "bg-ink text-white" : "hover:bg-ink/5"} w-full rounded-xl px-3 py-3 text-start text-sm`}>{ar ? lesson.title_ar : lesson.title_fr}</button>)}</div>)}</div></aside>
    <article className="rounded-3xl border border-ink/10 bg-white p-5 sm:p-8"><div className="aspect-video rounded-2xl bg-ink p-5 text-white sm:p-8">{selected?.video_url?.startsWith("http") ? <iframe title={ar ? selected.title_ar ?? "" : selected.title_fr ?? ""} src={selected.video_url} className="h-full w-full rounded-xl" allowFullScreen /> : <div className="grid h-full place-items-center text-center"><div><p className="text-xs uppercase tracking-[0.15em] text-gold">{selected?.video_provider ?? (ar ? "درس" : "Leçon")}</p><p className="mt-3 text-white/70">{ar ? "المحتوى المحمي متاح من خلال حسابك." : "Le contenu protégé est disponible dans votre espace."}</p></div></div>}</div>{selected ? <><p className="mt-7 text-sm text-gold-dark">{ar ? selected.module?.title_ar : selected.module?.title_fr}</p><h2 className="mt-2 text-3xl font-semibold">{ar ? selected.title_ar : selected.title_fr}</h2><p className="mt-4 whitespace-pre-line leading-7 text-ink/65">{ar ? selected.description_ar || selected.description_fr : selected.description_fr || selected.description_ar}</p><div className="mt-8"><h3 className="text-lg font-semibold">{ar ? "الموارد" : "Ressources"}</h3><button type="button" onClick={() => select(selected.id)} className="mt-3 text-sm font-semibold text-gold-dark underline">{ar ? "تحديث الموارد" : "Charger les ressources"}</button><div className="mt-3 grid gap-2">{resources.map((resource) => <a key={resource.id} href={resource.signed_url ?? resource.external_url ?? "#"} target="_blank" rel="noreferrer" className="rounded-xl border border-ink/10 p-3 text-sm font-semibold">{ar ? resource.title_ar : resource.title_fr} ↗</a>)}</div></div><div className="mt-8 flex flex-wrap justify-between gap-3"><button type="button" onClick={() => select(ordered[Math.max(0, ordered.findIndex((item) => item.id === selected.id) - 1)]?.id)} disabled={ordered.findIndex((item) => item.id === selected.id) <= 0} className="rounded-full border border-ink/15 px-5 py-3 text-sm font-semibold disabled:opacity-40">← {ar ? "السابق" : "Précédent"}</button><button type="button" onClick={() => select(ordered[Math.min(ordered.length - 1, ordered.findIndex((item) => item.id === selected.id) + 1)]?.id)} disabled={ordered.findIndex((item) => item.id === selected.id) >= ordered.length - 1} className="rounded-full bg-ink px-5 py-3 text-sm font-semibold text-white disabled:opacity-40">{ar ? "التالي" : "Suivant"} →</button></div></> : <p>{ar ? "لا توجد دروس منشورة بعد." : "Aucune leçon publiée pour le moment."}</p>}</article>
    <section className="lg:col-span-2"><h2 className="text-2xl font-semibold">{ar ? "البثوث المباشرة القادمة" : "Sessions Live à venir"}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{lives.map((live) => <div key={live.id} className="rounded-2xl border border-ink/10 bg-white p-5"><p className="font-semibold">{ar ? live.title_ar : live.title_fr}</p><p className="mt-2 text-sm text-ink/60">{new Date(live.starts_at).toLocaleString(ar ? "ar-DZ" : "fr-FR")}</p><a href={live.join_url ?? "#"} target="_blank" rel="noreferrer" className="mt-4 inline-flex rounded-full bg-ink px-4 py-2 text-sm font-semibold text-white">{ar ? "الانضمام" : "Rejoindre"} ↗</a></div>)}</div></section>
  </div>;
}
