"use client";
import { useEffect, useState } from "react";
type Locale = "fr" | "ar";
type Profile = { full_name?: string | null; specialty?: string | null; years_experience?: number | null; linkedin_url?: string | null; website_url?: string | null; public_title_fr?: string | null; public_title_ar?: string | null; public_bio_fr?: string | null; public_bio_ar?: string | null; public_photo_path?: string | null };
type RequestState = { status?: string; rejection_reason?: string | null } | null;
export default function TrainerProfileForm({ locale }: { locale: Locale }) {
  const ar = locale === "ar"; const [profile, setProfile] = useState<Profile>({}); const [request, setRequest] = useState<RequestState>(null); const [busy, setBusy] = useState(true); const [photoBusy, setPhotoBusy] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { fetch("/api/trainer/profile").then((r) => r.json()).then((d) => { setProfile(d.profile ?? {}); setRequest(d.request ?? null); }).catch(() => setMessage(ar ? "تعذر تحميل الملف." : "Profil indisponible.")).finally(() => setBusy(false)); }, [ar]);
  function field(key: keyof Profile, label: string, type = "text") { return <label className="grid gap-2 text-sm font-semibold">{label}<input type={type} value={String(profile[key] ?? "")} onChange={(e) => setProfile({ ...profile, [key]: type === "number" ? Number(e.target.value) : e.target.value })} className="min-h-11 rounded-xl border border-ink/15 bg-white px-3 font-normal" /></label>; }
  async function save(e: React.FormEvent) { e.preventDefault(); setBusy(true); setMessage(""); const r = await fetch("/api/trainer/profile", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(profile) }); const d = await r.json().catch(() => ({})); setMessage(d.message ?? d.error ?? (r.ok ? (ar ? "تم الحفظ." : "Enregistré.") : "Erreur.")); if (r.ok) setRequest({ status: "pending" }); setBusy(false); }
  async function photo(file?: File) { if (!file) return; setPhotoBusy(true); setMessage(""); const body = new FormData(); body.append("file", file); const r = await fetch("/api/trainer/profile/photo", { method: "POST", body }); const d = await r.json().catch(() => ({})); if (r.ok) { setProfile({ ...profile, public_photo_path: d.path }); setMessage(ar ? "تم تحديث الصورة." : "Photo envoyée."); } else setMessage(d.error ?? (ar ? "تعذر رفع الصورة." : "Téléversement impossible.")); setPhotoBusy(false); }
  async function removePhoto() { setPhotoBusy(true); const r = await fetch("/api/trainer/profile/photo", { method: "DELETE" }); if (r.ok) setProfile({ ...profile, public_photo_path: null }); setPhotoBusy(false); }
  const status = request?.status === "pending" ? (ar ? "في انتظار التحقق" : "En attente de validation") : request?.status === "approved" ? (ar ? "تمت الموافقة" : "Approuvé") : request?.status === "rejected" ? (ar ? "تم الرفض" : "Refusé") : "";
  return <form onSubmit={save} dir={ar ? "rtl" : "ltr"} className="mt-8 grid gap-6 rounded-3xl border border-ink/10 bg-white p-6 shadow-sm"><section><h2 className="text-xl font-semibold">{ar ? "صورة الملف العام" : "Photo de profil"}</h2><div className="mt-4 flex flex-wrap items-center gap-4"><div className="grid h-28 w-28 place-items-center overflow-hidden rounded-2xl bg-sand text-center text-xs text-ink/50">{profile.public_photo_path ? <img src={profile.public_photo_path} alt="" className="h-full w-full object-cover" /> : (ar ? "لا توجد صورة" : "Aucune photo")}</div><div className="grid gap-2"><input type="file" accept="image/jpeg,image/png,image/webp" disabled={photoBusy} onChange={(e) => void photo(e.target.files?.[0])} className="max-w-full rounded-xl border p-3 text-sm" /><button type="button" onClick={() => void removePhoto()} disabled={photoBusy || !profile.public_photo_path} className="text-start text-sm font-semibold text-red-700 disabled:opacity-40">{ar ? "حذف الصورة" : "Supprimer la photo"}</button><p className="text-xs text-ink/50">JPEG, PNG, WebP · 5 Mo</p></div></div></section><section><h2 className="text-xl font-semibold">{ar ? "المعلومات المهنية" : "Informations professionnelles"}</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">{field("full_name", ar ? "الاسم الكامل" : "Nom complet")}{field("specialty", ar ? "التخصص" : "Spécialité")}{field("years_experience", ar ? "سنوات الخبرة" : "Années d’expérience", "number")}{field("public_title_fr", "Titre public FR")}{field("public_title_ar", "العنوان العام AR")}{field("linkedin_url", "LinkedIn", "url")}{field("website_url", ar ? "الموقع" : "Site web", "url")}</div></section><section><h2 className="text-xl font-semibold">{ar ? "السيرة الذاتية العامة" : "Biographie publique"}</h2><div className="mt-4 grid gap-4"><label className="grid gap-2 text-sm font-semibold">Bio FR<textarea rows={4} value={String(profile.public_bio_fr ?? "")} onChange={(e) => setProfile({ ...profile, public_bio_fr: e.target.value })} className="rounded-xl border border-ink/15 p-3 font-normal" /></label><label className="grid gap-2 text-sm font-semibold">السيرة AR<textarea dir="rtl" rows={4} value={String(profile.public_bio_ar ?? "")} onChange={(e) => setProfile({ ...profile, public_bio_ar: e.target.value })} className="rounded-xl border border-ink/15 p-3 font-normal" /></label></div></section>{status && <p role="status" className="rounded-xl bg-gold/15 p-3 text-sm font-semibold">{status}</p>}{message && <p role="status" className="rounded-xl bg-ink/5 p-3 text-sm">{message}</p>}<button disabled={busy} className="min-h-12 rounded-full bg-ink px-5 text-sm font-semibold text-white disabled:opacity-50">{busy ? (ar ? "جارٍ التحميل…" : "Chargement…") : (ar ? "إرسال للمراجعة" : "Soumettre pour validation")}</button></form>;
}
