import Link from "next/link";
import { requireLmsRole, localizedValue } from "@/lib/lms";

type Course = { id: string; title: string | null; slug: string | null; status: string | null; excerpt: string | null; cover_url?: string | null };
export const dynamic = "force-dynamic";
export default async function TrainerDashboard({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: rawLocale } = await params; const locale = rawLocale === "ar" ? "ar" : "fr"; const ar = locale === "ar"; const { supabase, profile } = await requireLmsRole("trainer", locale);
  const { data: courseData } = await supabase.from("courses").select("id,title,slug,status,excerpt,cover_url").eq("trainer_id", profile!.trainer_id).order("display_order", { ascending: true });
  const courses = (courseData ?? []) as Course[]; const ids = courses.map((course) => course.id);
  const [{ data: modules }, { data: lives }] = ids.length ? await Promise.all([supabase.from("lms_modules").select("id,course_id").in("course_id", ids), supabase.from("lms_live_sessions").select("id,course_id,title_fr,title_ar,starts_at").in("course_id", ids).gte("starts_at", new Date().toISOString()).eq("status", "scheduled").order("starts_at").limit(5)]) : [{ data: [] }, { data: [] }];
  const moduleIds = (modules ?? []).map((item) => item.id); const { data: lessons } = moduleIds.length ? await supabase.from("lms_lessons").select("id").in("module_id", moduleIds) : { data: [] };
  const name = profile?.display_name || (ar ? "المدرب" : "Formateur"); const upcoming = (lives ?? [])[0] as { title_fr?: string | null; title_ar?: string | null; starts_at?: string } | undefined;
  const copy = ar ? { dashboard: "لوحة المدرب", welcome: `مرحباً، ${name}`, intro: "أدر دوراتك ومحتواك التعليمي باحترافية.", courses: "الدورات المكلّف بها", modules: "الوحدات", lessons: "الدروس", live: "الجلسات القادمة", next: "الجلسة المباشرة القادمة", recent: "النشاط الأخير", profile: "ملفي الشخصي", manage: "إدارة الدورة", empty: "لا توجد دورات مرتبطة بهذا الحساب." } : { dashboard: "Tableau de bord", welcome: `Bonjour, ${name}`, intro: "Gérez vos formations et votre contenu pédagogique.", courses: "Formations assignées", modules: "Modules", lessons: "Leçons", live: "Sessions à venir", next: "Prochaine session Live", recent: "Activité récente", profile: "Mon profil", manage: "Gérer la formation", empty: "Aucune formation n’est liée à ce compte." };
  return <main dir={ar ? "rtl" : "ltr"} className="min-h-screen bg-background"><header className="bg-ink px-5 py-5 text-white"><div className="mx-auto flex max-w-6xl justify-between gap-4"><Link href={`/${locale}`} className="font-semibold tracking-[0.08em]">Meritify <span className="text-gold">ACADEMY</span></Link><div className="flex items-center gap-4"><Link href={`/${locale}/trainer/profile`} className="text-sm text-white/70">{copy.profile}</Link><form action="/api/lms/logout" method="post"><button className="text-sm text-white/70">{ar ? "خروج" : "Se déconnecter"}</button></form></div></div></header><section className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><p className="eyebrow text-gold-dark">{copy.dashboard}</p><h1 className="mt-3 text-3xl font-semibold sm:text-5xl">{copy.welcome}</h1><p className="mt-3 text-ink/60">{copy.intro}</p><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric label={copy.courses} value={courses.length}/><Metric label={copy.modules} value={modules?.length ?? 0}/><Metric label={copy.lessons} value={lessons?.length ?? 0}/><Metric label={copy.live} value={lives?.length ?? 0}/></div><div className="mt-8 grid gap-6 lg:grid-cols-[1.4fr_.8fr]"><section><h2 className="text-2xl font-semibold">{copy.courses}</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">{courses.map((course) => <article key={course.id} className="rounded-3xl border border-ink/10 bg-white p-5 shadow-sm"><p className="text-xs uppercase tracking-[.15em] text-gold-dark">{course.status ?? "—"}</p><h3 className="mt-2 text-xl font-semibold">{course.title}</h3><p className="mt-2 line-clamp-2 text-sm text-ink/55">{course.excerpt}</p><Link href={`/${locale}/trainer/courses/${course.id}`} className="mt-5 inline-flex min-h-10 items-center rounded-full bg-ink px-4 text-sm font-semibold text-white">{copy.manage} ↗</Link></article>)}{!courses.length && <p className="rounded-2xl bg-white p-6 text-sm text-ink/55">{copy.empty}</p>}</div></section><aside className="grid gap-4"><section className="rounded-3xl bg-ink p-6 text-white"><p className="text-sm text-gold">{copy.next}</p>{upcoming ? <><h2 className="mt-3 text-xl font-semibold">{localizedValue(locale, upcoming.title_fr, upcoming.title_ar)}</h2><p className="mt-2 text-sm text-white/65">{new Date(upcoming.starts_at ?? "").toLocaleString(locale === "ar" ? "ar-DZ" : "fr-FR")}</p></> : <p className="mt-3 text-sm text-white/60">—</p>}</section><section className="rounded-3xl border border-ink/10 bg-white p-6"><h2 className="text-xl font-semibold">{copy.recent}</h2><p className="mt-3 text-sm text-ink/55">{ar ? "تظهر هنا آخر تحديثات المحتوى." : "Les dernières mises à jour de vos contenus apparaîtront ici."}</p></section></aside></div></section></main>;
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl border border-ink/10 bg-white p-4"><p className="text-xs text-ink/55">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></div>; }
