import { NextResponse } from "next/server";
import { requireAdmin } from "@/lib/supabase/admin";
import { createServiceClient } from "@/lib/supabase/service";
import { isSameOrigin } from "@/lib/security/request";

export async function GET() { await requireAdmin(); const service = createServiceClient(); const result = await service.from("trainer_profile_change_requests").select("id,trainer_id,proposed_changes,status,created_at,rejection_reason").order("created_at", { ascending: false }); if (result.error) return NextResponse.json({ error: "Migration de validation du profil requise." }, { status: 503 }); const ids = [...new Set((result.data ?? []).map((row) => row.trainer_id))]; const trainers = ids.length ? await service.from("trainers_crm").select("id,full_name,public_title_fr,public_title_ar,public_bio_fr,public_bio_ar,public_photo_path").in("id", ids) : { data: [] }; const map = new Map((trainers.data ?? []).map((row) => [row.id, row])); return NextResponse.json({ requests: (result.data ?? []).map((row) => ({ ...row, trainer: map.get(row.trainer_id) ?? null })) }); }
export async function PATCH(request: Request) {
  if (!isSameOrigin(request)) return NextResponse.json({ error: "Origine non autorisée." }, { status: 403 }); const { user } = await requireAdmin(); const body = await request.json().catch(() => null) as { id?: string; decision?: string; rejection_reason?: string } | null; if (!body?.id || !["approved", "rejected"].includes(body.decision ?? "")) return NextResponse.json({ error: "Décision invalide." }, { status: 400 });
  const service = createServiceClient(); const pending = await service.from("trainer_profile_change_requests").select("id,trainer_id,proposed_changes,status").eq("id", body.id).eq("status", "pending").maybeSingle(); if (!pending.data) return NextResponse.json({ error: "Demande introuvable ou déjà traitée." }, { status: 404 });
  const changes = pending.data.proposed_changes as Record<string, unknown>;
  if (body.decision === "approved") { const current = await service.from("trainers_crm").select("public_photo_path").eq("id", String(pending.data.trainer_id)).maybeSingle(); const update = await service.from("trainers_crm").update(changes as never).eq("id", String(pending.data.trainer_id)); if (update.error) return NextResponse.json({ error: "Profil formateur introuvable." }, { status: 404 }); const oldPath = typeof current.data?.public_photo_path === "string" ? current.data.public_photo_path : null; if (typeof changes.public_photo_path === "string" && oldPath?.startsWith(`trainers/${String(pending.data.trainer_id)}/profile/`)) await service.storage.from("trainer-profile-images").remove([oldPath]); }
  const proposedPhoto = typeof changes.public_photo_path === "string" ? changes.public_photo_path : null;
  if (body.decision === "rejected" && proposedPhoto?.startsWith(`trainers/${String(pending.data.trainer_id)}/profile/`)) await service.storage.from("trainer-profile-images").remove([proposedPhoto]);
  const result = await service.from("trainer_profile_change_requests").update({ status: body.decision, reviewed_by: user.id, reviewed_at: new Date().toISOString(), rejection_reason: body.decision === "rejected" ? body.rejection_reason?.trim() || null : null }).eq("id", body.id); if (result.error) return NextResponse.json({ error: "Impossible de clôturer la demande." }, { status: 500 }); return NextResponse.json({ ok: true });
}
