"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";
import { useParams } from "next/navigation";

export default function LmsLoginPage() {
  const params = useParams<{ locale: string }>();
  const locale = params.locale === "ar" ? "ar" : "fr";
  const ar = locale === "ar";
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [inviteMode, setInviteMode] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(false);
  useEffect(() => { const params = new URLSearchParams(window.location.search); setInviteMode(params.get("invite") === "1"); if (params.get("invite_error") === "1") setError(ar ? "تعذر قبول الدعوة. اطلب من الإدارة إرسال دعوة جديدة." : "L’invitation n’a pas pu être acceptée. Demandez une nouvelle invitation à l’administration."); }, [ar]);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); setNotice(""); const client = createClient(); if (inviteMode) { if (password.length < 8 || password !== confirmPassword) { setError(ar ? "اختر كلمة مرور من 8 أحرف وتأكد من تطابقها." : "Choisissez un mot de passe d’au moins 8 caractères et confirmez-le."); setLoading(false); return; } const { error: updateError } = await client.auth.updateUser({ password }); if (updateError) { setError(ar ? "تعذر إعداد كلمة المرور." : "La configuration du mot de passe a échoué."); setLoading(false); return; } const response = await fetch("/api/lms/me"); const data = await response.json().catch(() => ({})); window.location.assign(data.redirect ?? `/${locale}/student`); return; } const { error: authError } = await client.auth.signInWithPassword({ email: email.trim(), password }); if (authError) { setError(ar ? "تعذر تسجيل الدخول. تحقق من البيانات." : "Connexion impossible. Vérifiez vos identifiants."); setLoading(false); return; } const response = await fetch("/api/lms/me"); const data = await response.json().catch(() => ({})); window.location.assign(data.redirect ?? `/${locale}/student`); }
  async function reset() { if (!email.trim()) { setError(ar ? "أدخل بريدك الإلكتروني أولاً." : "Saisissez d’abord votre e-mail."); return; } const { error: resetError } = await createClient().auth.resetPasswordForEmail(email.trim(), { redirectTo: `${window.location.origin}/${locale}/login` }); setError(resetError ? (ar ? "تعذر إرسال رابط الاستعادة." : "Le lien de récupération n’a pas pu être envoyé.") : ""); setNotice(resetError ? "" : (ar ? "تم إرسال رابط استعادة كلمة المرور." : "Un lien de récupération a été envoyé.")); }
  return <main dir={ar ? "rtl" : "ltr"} className="grid min-h-screen place-items-center bg-ink px-5 py-10 text-ink"><div className="w-full max-w-md rounded-3xl bg-background p-7 shadow-2xl sm:p-10"><Link href={`/${locale}`} className="font-semibold tracking-[0.08em]">Meritify <span className="text-gold-dark">ACADEMY</span></Link><p className="eyebrow mt-12 text-gold-dark">{ar ? "منصة التعلّم" : "Espace apprenant"}</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.06em]">{inviteMode ? (ar ? "إعداد حسابك" : "Configurer votre accès") : (ar ? "تسجيل الدخول" : "Connexion LMS")}</h1><p className="mt-4 text-sm leading-6 text-ink/60">{inviteMode ? (ar ? "اختر كلمة مرور آمنة للوصول إلى مساحة المدرب." : "Choisissez un mot de passe sécurisé pour accéder à votre espace formateur.") : (ar ? "الوصول إلى دوراتك ومواردك التعليمية." : "Accédez à vos formations et ressources pédagogiques.")}</p><form onSubmit={submit} className="mt-8 grid gap-5">{!inviteMode && <label className="grid gap-2 text-sm font-semibold">{ar ? "البريد الإلكتروني" : "E-mail"}<input className="min-h-12 rounded-xl border border-ink/15 bg-white px-4 font-normal" type="email" value={email} onChange={e => setEmail(e.target.value)} required autoComplete="email" /></label>}<label className="grid gap-2 text-sm font-semibold">{ar ? "كلمة المرور" : "Mot de passe"}<input className="min-h-12 rounded-xl border border-ink/15 bg-white px-4 font-normal" type="password" value={password} onChange={e => setPassword(e.target.value)} required autoComplete={inviteMode ? "new-password" : "current-password"} /></label>{inviteMode && <label className="grid gap-2 text-sm font-semibold">{ar ? "تأكيد كلمة المرور" : "Confirmer le mot de passe"}<input className="min-h-12 rounded-xl border border-ink/15 bg-white px-4 font-normal" type="password" value={confirmPassword} onChange={e => setConfirmPassword(e.target.value)} required autoComplete="new-password" /></label>}{error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700" role="alert">{error}</p>}{notice && <p className="rounded-xl bg-green-50 p-3 text-sm text-green-700">{notice}</p>}<button disabled={loading} className="min-h-12 rounded-full bg-ink px-6 text-sm font-semibold text-white disabled:opacity-60">{loading ? (ar ? "جارٍ المعالجة…" : "Traitement…") : inviteMode ? (ar ? "تأكيد الحساب ↗" : "Activer mon accès ↗") : (ar ? "دخول ↗" : "Se connecter ↗")}</button></form>{!inviteMode && <button type="button" onClick={reset} className="mt-5 text-sm font-semibold text-gold-dark underline">{ar ? "نسيت كلمة المرور؟" : "Mot de passe oublié ؟"}</button>}</div></main>;
}
