import { NextResponse } from "next/server";
import { createServiceClient } from "@/lib/supabase/service";
import { requireAdmin } from "@/lib/supabase/admin";
import { isSameOrigin } from "@/lib/security/request";

type ContentType = "module" | "lesson" | "live";

function errorResponse(message: string, status = 400) { return NextResponse.json({ error: message }, { status }); }

function values(type: ContentType, body: Record<string, unknown>) {
  if (type === "module") return { course_id: body.course_id, title_fr: String(body.title_fr ?? "").trim(), title_ar: String(body.title_ar ?? "").trim(), description_fr: String(body.description_fr ?? "").trim() || null, description_ar: String(body.description_ar ?? "").trim() || null, display_order: Number(body.display_order ?? body.sort_order ?? 0), published: typeof body.published === "boolean" ? body.published : body.status === "published" };
  if (type === "lesson") return { module_id: body.module_id, title_fr: String(body.title_fr ?? "").trim(), title_ar: String(body.title_ar ?? "").trim(), description_fr: String(body.description_fr ?? body.content_fr ?? "").trim() || null, description_ar: String(body.description_ar ?? body.content_ar ?? "").trim() || null, video_provider: body.video_provider ? String(body.video_provider) : null, video_asset_id: String(body.video_asset_id ?? "").trim() || null, duration_seconds: body.duration_seconds === "" || body.duration_seconds == null ? null : Number(body.duration_seconds), display_order: Number(body.display_order ?? body.sort_order ?? 0), published: typeof body.published === "boolean" ? body.published : body.status === "published" };
  return { course_id: body.course_id, session_id: String(body.session_id ?? "").trim() || null, title_fr: String(body.title_fr ?? "").trim(), title_ar: String(body.title_ar ?? "").trim(), provider: String(body.provider ?? "google_meet"), join_url: String(body.join_url ?? body.meeting_url ?? "").trim(), starts_at: body.starts_at, ends_at: body.ends_at || null, status: body.status === "cancelled" ? "cancelled" : body.status === "completed" ? "completed" : "scheduled" };
}

export async function POST(request: Request) { try { if (!isSameOrigin(request)) return errorResponse("Origine non autorisée.", 403); await requireAdmin(); const body = await request.json() as Record<string, unknown>; const type = body.type as ContentType; if (!["module", "lesson", "live"].includes(type)) return errorResponse("Type de contenu invalide."); const data = values(type, body) as Record<string, unknown>; const required = type === "lesson" ? ["module_id", "title_fr", "title_ar"] : type === "live" ? ["course_id", "title_fr", "title_ar", "join_url", "starts_at"] : ["course_id", "title_fr", "title_ar"]; if (required.some(key => !data[key])) return errorResponse("Les champs obligatoires sont incomplets."); const result = await createServiceClient().from(type === "module" ? "lms_modules" : type === "lesson" ? "lms_lessons" : "lms_live_sessions").insert(data).select().single(); if (result.error) return errorResponse("Impossible d’enregistrer le contenu LMS.", 500); return NextResponse.json({ item: result.data }); } catch (error) { console.error("LMS content create failed:", error instanceof Error ? error.message : "unknown"); return errorResponse("Service LMS indisponible.", 503); } }

export async function PATCH(request: Request) { try { if (!isSameOrigin(request)) return errorResponse("Origine non autorisée.", 403); await requireAdmin(); const body = await request.json() as Record<string, unknown>; const type = body.type as ContentType; const id = String(body.id ?? ""); if (!id || !["module", "lesson", "live"].includes(type)) return errorResponse("Contenu invalide."); const table = type === "module" ? "lms_modules" : type === "lesson" ? "lms_lessons" : "lms_live_sessions"; const service = createServiceClient(); const existing = await service.from(table).select("*").eq("id", id).single(); if (existing.error) return errorResponse("Contenu introuvable.", 404); const result = await service.from(table).update(values(type, { ...existing.data, ...body }) as Record<string, unknown>).eq("id", id).select().single(); if (result.error) return errorResponse("Impossible de modifier le contenu LMS.", 500); return NextResponse.json({ item: result.data }); } catch (error) { console.error("LMS content update failed:", error instanceof Error ? error.message : "unknown"); return errorResponse("Service LMS indisponible.", 503); } }

export async function DELETE(request: Request) { try { if (!isSameOrigin(request)) return errorResponse("Origine non autorisée.", 403); await requireAdmin(); const body = await request.json() as { type?: ContentType; id?: string }; const table = body.type === "module" ? "lms_modules" : body.type === "lesson" ? "lms_lessons" : body.type === "live" ? "lms_live_sessions" : null; if (!table || !body.id) return errorResponse("Contenu invalide."); const result = await createServiceClient().from(table).delete().eq("id", body.id); if (result.error) return errorResponse("Impossible de supprimer le contenu LMS.", 500); return NextResponse.json({ ok: true }); } catch (error) { console.error("LMS content delete failed:", error instanceof Error ? error.message : "unknown"); return errorResponse("Service LMS indisponible.", 503); } }
